Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2021-07, with the labels that each got.

#41 bump version to 1.5.1
  setup.cfg
Labels: Size:XS

#43 Add status ConfigurationProgressing to NNCP
  ocp_resources/node_network_configuration_policy.py
Labels: Size:XS

#44 bump version to 1.5.2
  setup.cfg
Labels: Size:XS

#42 Readme add pypi link
  .pre-commit-config.yaml
  README.md
Labels: Size:XS

#23 Allow vmi pause state change timeout to include initial CRD state
  ocp_resources/virtual_machine.py
Labels: Size:XS

#51 Storage: update priority class
  ocp_resources/priority_class.py
Labels: Size:S, Verified

#45 Migration ToolKit For Virtualization Common Module
  ocp_resources/mtv.py
  ocp_resources/resource.py
Labels: Size:L, Verified

#54 Add OWNERS file
  OWNERS
Labels: Size:XS

#46 Migration ToolKit For Virtualization Plan Resource Handler
  ocp_resources/mtv.py
  ocp_resources/plan.py
Labels: Size:L, Verified

#50 Migration ToolKit For Virtualization Provider Resource Handler
  ocp_resources/provider.py
Labels: Size:L, Verified, lgtm

#49 Migration ToolKit For Virtualization Migration Resource Handler
  ocp_resources/migration.py
Labels: Size:L, Verified, lgtm

#48 Migration ToolKit For Virtualization NetworkMap Resource Handler
  ocp_resources/network_map.py
Labels: Size:L, Verified, lgtm

#47 Migration ToolKit For Virtualization StorageMap Resource Handler
  ocp_resources/storage_map.py
Labels: Size:L, Verified, lgtm

#25 Add Benchmark resource
  ocp_resources/benchmark.py
  ocp_resources/resource.py
Labels: Size:M, lgtm

#61 Create issue/RFE report templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, lgtm, release-note-none, size/M

#62 Add release note to PR template
  .github/pull_request_template.md
Labels: release-note-none, size/S

#58 add timeout arg to ProjectRequest.__init__
  ocp_resources/project.py
Labels: approved, release-note-none, size/S

#57 Mtv
  ocp_resources/migration.py
  ocp_resources/mtv.py
  ocp_resources/network_map.py
  ocp_resources/plan.py
  ocp_resources/provider.py
  ocp_resources/storage_map.py
Labels: approved, release-note, size/L

#64 README: Update changelog section
  README.md
Labels: approved, release-note-none, size/XS

#63 bump version to 1.5.3
  setup.cfg
Labels: release-note, size/XS

#65 v1.5.3 changelog
  CHANGELOG.md
Labels: approved, release-note-none, size/S

#70 README: Update PR dependency section
  README.md
Labels: approved, release-note-none, size/XS

#73 Update vm container image
  tests/manifests/vm.yaml
Labels: approved, release-note-none, size/XS

#74 Remove nudge_delete
  ocp_resources/namespace.py
  ocp_resources/project.py
  ocp_resources/utils.py
Labels: Verified, approved, release-note, size/S
