Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2021-10, with the labels that each got.

#117 use exceptions_dict
  ocp_resources/benchmark.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/constants.py
  ocp_resources/daemonset.py
  ocp_resources/deployment.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: Verified, size/S, Approve, Ready for merge

#193 change name to match with existing resources
  ocp_resources/console_quick_start.py
Labels: Verified, size/XS, Approve

#188 Add PodDisruptionBudget class
  ocp_resources/pod_disruption_budget.py
  ocp_resources/resource.py
Labels: Verified, size/M, Approve

#113 Run using Hypervisor Connection URI if Non-Root Virt-Launcher Pods
  ocp_resources/virtual_machine_instance.py
Labels: Verified, size/S, Approve

#199 update ApiVersion
  ocp_resources/resource.py
Labels: Verified, Approve, Ready for merge

#208 rename virtual_machine_import_configs to match standard naming convention
  ocp_resources/vm_import_config.py
Labels: Verified, size/XS, Approve, Ready for merge

#196 Improve NNCE logs when NNCP fail
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/S, Approve

#210 Add new entry to Resource.ApiGroup for Infra features
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#103 Remove deprecated TimeoutSampler arguments
  ocp_resources/utils.py
  tests/unittests/test_utils.py
Labels: Verified, size/XS, Approve, Ready for merge

#215 Fix docs link
  README.md
Labels: Verified, size/XS, Approve, Ready for merge

#218 Rename master branch to main
  README.md
  scripts/release.sh
Labels: Verified, size/XS, Approve
