Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2021-12, with the labels that each got.

#261 Rename StorageClass.Provisioner.LOCAL_BLOCK
  ocp_resources/storage_class.py
Labels: Verified, size/XS, Approve, Ready for merge

#259 Add StorageProfile resource
  ocp_resources/storage_profile.py
Labels: Verified, size/XS, Approve, Ready for merge

#245 add etcd timeout to DEFAULT_CLUSTER_RETRY_EXCEPTIONS
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#263 Add hostpath-csi storage class
  ocp_resources/storage_class.py
Labels: Verified, size/XS, Approve, Ready for merge

#267 NNCP: add support for OVS bridge
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/XS, Approve, Ready for merge

#251 Expose wait_timeout in MTV wait methods
  ocp_resources/mtv.py
Labels: Verified, size/XS, Approve, Ready for merge

#269 add resource ImageStream
  ocp_resources/image_stream.py
Labels: Verified, size/XS, Approve, Ready for merge

#265 Added support for maxUnavailable
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/XS, Approve, Ready for merge

#275 Add ApiGroup NODE_LABELLER_KUBEVIRT_IO
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#283 Resource: delete should use delete_timeout
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve

#279 Namespace: remove client_wait_deleted()
  ocp_resources/namespace.py
Labels: Verified, size/XS, Approve

#285 Get NNCEs for the right NNCP
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/XS, Approve, Ready for merge

#289 Event - use api version
  ocp_resources/event.py
Labels: Verified, size/XS, Approve, Ready for merge

#287 Data source - add pvc property
  ocp_resources/data_source.py
Labels: Verified, size/S, Approve, Ready for merge

#293 MTV: Adding PLAN_FAILED condition message
  ocp_resources/mtv.py
Labels: Verified, size/XS, Approve, Ready for merge

#271 Add data import cron resource
  ocp_resources/data_import_cron.py
Labels: Verified, size/M, Ready for merge

#281 Include new conditions.reason as part of maxUnavailable support.
  ocp_resources/node_network_configuration_enactment.py
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/S, Ready for merge

#297 Expose delete_timeout arg
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/cluster_role.py
  ocp_resources/configmap.py
  ocp_resources/constants.py
  ocp_resources/daemonset.py
  ocp_resources/data_import_cron.py
  ocp_resources/data_source.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/hook.py
  ocp_resources/host.py
  ocp_resources/hostpath_provisioner.py
  ocp_resources/hyperconverged.py
  ocp_resources/kube_descheduler.py
  ocp_resources/machine.py
  ocp_resources/machine_health_check.py
  ocp_resources/machine_set.py
  ocp_resources/migration.py
  ocp_resources/namespace.py
  ocp_resources/network_map.py
  ocp_resources/node_maintenance.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/operator_group.py
  ocp_resources/operator_source.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/plan.py
  ocp_resources/pod.py
  ocp_resources/pod_disruption_budget.py
  ocp_resources/priority_class.py
  ocp_resources/project.py
  ocp_resources/provider.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
  ocp_resources/route.py
  ocp_resources/secret.py
  ocp_resources/sriov_network.py
  ocp_resources/sriov_network_node_policy.py
  ocp_resources/storage_map.py
  ocp_resources/subscription.py
  ocp_resources/upload_token_request.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_Instance_replica_set.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_instance_migration.py
  ocp_resources/virtual_machine_instance_preset.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: Verified, size/L, Ready for merge

#299 log YAML output on create, update and delete
  README.md
  ocp_resources/benchmark.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/data_source.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/event.py
  ocp_resources/logger.py
  ocp_resources/machine_set.py
  ocp_resources/mtv.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/route.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/upload_token_request.py
  ocp_resources/utils.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
  setup.py
Labels: Verified, size/L, Ready for merge

#277 Wait for replicas
  ocp_resources/deployment.py
Labels: Verified, size/XS, Ready for merge

#301 Add bind_immediate_annotation for dataimportcron
  ocp_resources/data_import_cron.py
Labels: Verified, size/XS, Ready for merge

#304 call to_dict if body is not dict type
  ocp_resources/resource.py
Labels: Verified, size/XS, Ready for merge

#309 Add hana workload
  ocp_resources/template.py
Labels: Verified, size/XS

#313 Move log to delete()
  ocp_resources/resource.py
Labels: Verified, size/XS, Ready for merge

#317 Move log to delete(), add more information to log in clean_up()
  ocp_resources/resource.py
Labels: Verified, size/XS, Ready for merge

#319 NNCPConfigurationFailed: raise with error
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/XS, Ready for merge

#315 NNCP: support adding interfaces
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/M, Ready for merge

#323 Update README - add missing 'export' in command
  README.md
Labels: Verified, size/XS, Ready for merge
