Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2021-11, with the labels that each got.

#226 Add WFFC status to DV
  ocp_resources/datavolume.py
Labels: Verified, size/XS, Approve, Ready for merge

#228 Fixing 'cutover' position in migration mtv resource
  ocp_resources/migration.py
Labels: Verified, size/XS, Approve, Ready for merge

#234 Add OperatorCondition class
  ocp_resources/operator_condition.py
Labels: Verified, size/XS, Approve, Ready for merge

#236 Add python 3.10 support
  .pre-commit-config.yaml
  ocp_resources/utils.py
Labels: Verified, size/XS, Approve, Ready for merge

#240 Set MAX_SUPPORTED_API_VERSION > v2
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve

#238 Added support for hooks in the plan
  ocp_resources/hook.py
  ocp_resources/plan.py
Labels: Verified, size/M, Approve

#243 Add kind to log api version in _get_api_version
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#242 namespace resource: support get raw object in get() - Cherry-pick
  ocp_resources/resource.py
Labels: Verified, Approve, Ready for merge

#253 Add data source
  ocp_resources/data_source.py
Labels: Verified, size/S, Approve, Ready for merge

#257 Always call __exit__
  .flake8
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#255 Support skip teardown from os env
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#247 Adding MTV ForkliftController resource
  ocp_resources/forklift_controller.py
  ocp_resources/mtv.py
Labels: Verified, size/XS, Approve, Ready for merge
