Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2021-08, with the labels that each got.

#78 introduce autoflake
  .pre-commit-config.yaml
  ocp_resources/resource.py
Labels: approved, do-not-merge/release-note-label-needed, size/S

#72 Support create resources from YAML file
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cluster_role.py
  ocp_resources/configmap.py
  ocp_resources/datavolume.py
  ocp_resources/hostpath_provisioner.py
  ocp_resources/hyperconverged.py
  ocp_resources/kube_descheduler.py
  ocp_resources/machine.py
  ocp_resources/machine_health_check.py
  ocp_resources/migration.py
  ocp_resources/namespace.py
  ocp_resources/network_attachment_definition.py
  ocp_resources/network_map.py
  ocp_resources/node_maintenance.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/operator_group.py
  ocp_resources/operator_source.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/plan.py
  ocp_resources/pod.py
  ocp_resources/priority_class.py
  ocp_resources/project.py
  ocp_resources/provider.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
  ocp_resources/route.py
  ocp_resources/secret.py
  ocp_resources/sriov_network.py
  ocp_resources/sriov_network_node_policy.py
  ocp_resources/storage_map.py
  ocp_resources/subscription.py
  ocp_resources/upload_token_request.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: approved, release-note, size/XL

#80 Add ApiGroup VM_KUBEVIRT_IO
  ocp_resources/resource.py
  ocp_resources/template.py
Labels: Verified, approved, release-note-none, size/XS

#79 Move classes from virtual_machine.py to own files.
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_Instance_replica_set.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_instance_migration.py
  ocp_resources/virtual_machine_instance_preset.py
Labels: Verified, approved, release-note-none, size/XL

#82 CDI resource is not Namespace resource
  ocp_resources/cdi.py
Labels: Verified, approved, size/XS

#90 [CI] Update pre-commit pycln rev tag
  .pre-commit-config.yaml
Labels: size/XS

#92 Update readme
  .github/pull_request_template.md
  README.md
Labels: size/XS

#94 Fixing network section in Plan resource
  ocp_resources/plan.py
Labels: Verified, size/XS

#95 VolumeSnapshotClass resource is not namespaced
  ocp_resources/volume_snapshot.py
Labels: Verified, size/XS

#96 Split VolumeSnapshot, VolumeSnaphshotClass
  ocp_resources/volume_snapshot.py
  ocp_resources/volume_snapshot_class.py
Labels: Verified, size/XS

#99 Update changelog for version v1.5.11
  CHANGELOG.md
Labels: size/XS

#100 Add Infrastructure resource
  ocp_resources/infrastructure.py
Labels: Verified, size/XS

#101 V1.5.13
  CHANGELOG.md
  setup.cfg
Labels: size/XS

#102 NNCP: Fail when reason is NoMatchingNode
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/XS, Approve

#108 Add ServiceMeshMemberRoll resource for Service Mesh usage.
  ocp_resources/resource.py
  ocp_resources/service_mesh_member_roll.py
Labels: Verified, size/XS, Approve

#107 Add Gateway resource for Service Mesh usage.
  ocp_resources/gateway.py
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve

#104 k8s common resource labels
  ocp_resources/resource.py
Labels: size/XS, Approve

#109 Pod.execute: add ignore_rc flag
  ocp_resources/pod.py
Labels: Verified, size/XS, Approve

#110 Add DestinationRule resource for Service Mesh usage.
  ocp_resources/destination_rule.py
Labels: Verified, size/XS, Approve

#116 Annot 1 5 3 1
  ocp_resources/resource.py
  ocp_resources/template.py
Labels: Approve

#97 add machineset resource implementation
  ocp_resources/machine_set.py
Labels: Verified, size/L, Approve

#122 Adjust apiGroup and apiVersion for Gateway resource.
  ocp_resources/gateway.py
Labels: Verified, size/XS, Approve

#121 fix inheritence for resources
  ocp_resources/prometheus_rule.py
  ocp_resources/service_monitor.py
Labels: Verified, size/XS, Approve

#124 Add vm status
  ocp_resources/node_maintenance.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_instance.py
Labels: Verified, size/XS

#126 Adjust ApiGroup for SM Resources
  ocp_resources/destination_rule.py
  ocp_resources/service_mesh_member_roll.py
  ocp_resources/virtual_service.py
Labels: Verified, size/XS, Approve

#129 Add Service Mesh Peer Authentication Resource
  ocp_resources/peer_authentication.py
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#132 Add missing raise in create()
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#131 resource.delete: accept body
  ocp_resources/daemonset.py
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge
