Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2021-09, with the labels that each got.

#128 Add Vm printable status property
  ocp_resources/virtual_machine.py
Labels: Verified, size/XS, Approve

#134 pre-commit: add more checks
  .flake8
  .pre-commit-config.yaml
  ocp_resources/chaos_engine.py
  ocp_resources/event.py
  ocp_resources/machine_set.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/resource.py
  ocp_resources/utils.py
  ocp_resources/virtual_machine.py
Labels: Verified, size/S, Approve, Ready for merge

#133 Convert self.api() to property
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/deployment.py
  ocp_resources/mtv.py
  ocp_resources/persistent_volume.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
Labels: Verified, size/S, Approve, Ready for merge

#143 Node: No need to import NamespacedResource
  ocp_resources/node.py
Labels: Verified, size/XS, Approve, Ready for merge

#118 ResourceEditor: ResourceField sanitizing
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#140 dv.wait - raise TimeoutExpiredError if DV's status is Pending
  ocp_resources/datavolume.py
Labels: Verified, size/S, Approve, Ready for merge

#149 Add hostname property to Node
  ocp_resources/node.py
Labels: Verified, size/XS, Approve, Ready for merge

#164 Test action 1
  a
  b
  c
  d
  e
  f
Labels: Verified, size/XS, Approve

#151 Remove unneeded packages from setup.py
  setup.py
Labels: Verified, size/XS, Approve, Ready for merge

#154 TimeoutSampler: Print func and func kwargs before start loop
  ocp_resources/utils.py
Labels: Verified, size/S, Approve, Ready for merge

#168 host resource
  ocp_resources/host.py
  ocp_resources/mtv.py
Labels: Verified, size/M, Approve, Ready for merge

#175 Resource.labels does not return a dict, returns a ResourceField
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve

#170 Service Mesh Control Plane
  ocp_resources/service_mesh_control_plane.py
Labels: Verified, size/XS, Approve, Ready for merge

#176 Fix validate-resources errors
  ocp_resources/event.py
  ocp_resources/image_content_source_policy.py
  ocp_resources/oauth.py
  ocp_resources/replicaset.py
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve

#172 Validate resources
  .flake8
  .github/workflows/code-check.yml
  tests/test_validate_resources.py
  tox.ini
Labels: Verified, size/L, Approve

#178 TimeoutSampler: improve print for lambda calls
  ocp_resources/utils.py
Labels: Verified, size/XS, Approve, Ready for merge

#147 Add ConflictError to DEFAULT_CLUSTER_RETRY_EXCEPTIONS
  ocp_resources/resource.py
Labels: Verified, size/S, Approve, Ready for merge

#181 test_resources_definitions: Add exclude resource
  tests/test_validate_resources.py
Labels: Verified, size/XS, Approve, Ready for merge

#185 namespae resource: support get raw object in get()
  ocp_resources/resource.py
Labels: Verified, size/XS, Approve, Ready for merge

#191 Add taints property to node
  ocp_resources/node.py
Labels: Verified, size/XS, Approve, Ready for merge
