Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-09, with the labels that each got.

#793 add a generic function to execute virsh command
  ocp_resources/virtual_machine_instance.py
Labels: size/S, Verified

#797 add image resource
  ocp_resources/image.py
Labels: size/XS, Verified, Approved-by-myakove

#800 Revert "Remove saphana from template"
  ocp_resources/template.py
Labels: size/XS, Verified

#802 Add back FLAVOR_KUBEVIRT_IO
  ocp_resources/resource.py
Labels: size/XS, Verified

#804 Update KubeDescheduler
  ocp_resources/kube_descheduler.py
Labels: size/XS, Verified, Approved-by-myakove

#807 [4.11] Update KubeDescheduler (#804)
  ocp_resources/kube_descheduler.py
Labels: size/XS, Verified

#799 Add VirtualMachineExport resource
  ocp_resources/constants.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine_export.py
Labels: size/M, Verified, Approved-by-myakove

#811 Remove version from main branch
  setup.cfg
Labels: size/XS, Verified, Approved-by-rnetser

#806 removing matchlabels field from migration policy
  ocp_resources/migration_policy.py
Labels: size/XS, Verified, Approved-by-myakove

#815 remove FLAVOR_KUBEVIRT_IO
  ocp_resources/resource.py
Labels: size/XS, Verified, Approved-by-myakove, Approved-by-rnetser

#821 remove FLAVOR_KUBEVIRT_IO
  ocp_resources/resource.py
Labels: size/XS, Verified, Approved-by-rnetser

#824 Add APIServer resource
  ocp_resources/api_server.py
Labels: size/XS, Verified, Approved-by-rnetser

#828 Fix add_rule in ClusterRole
  ocp_resources/cluster_role.py
Labels: size/XS, Verified, Approved-by-rnetser

#830 Removing matchLabels from vmi_selector
  ocp_resources/migration_policy.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main

#835 WaitingForVolumeBinding VM status
  ocp_resources/virtual_machine.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main
