Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-10, with the labels that each got.

#840 pre-commit: update plugins
  .pre-commit-config.yaml
Labels: size/XS, Verified, branch-main

#850 pre-commit updates
  .pre-commit-config.yaml
  ocp_resources/resource.py
Labels: size/XS, branch-v4.8

#855 support subscription with separate name from package name
  ocp_resources/subscription.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main

#854 Method to wait for vm status ready
  ocp_resources/virtual_machine.py
Labels: size/S, Verified, branch-main, verify

#864 Rename vm.wait_for_status_ready
  ocp_resources/virtual_machine.py
Labels: size/XS, Verified, branch-main

#863 Change cluster preference from NamespacedResource to Resource
  ocp_resources/resource.py
  ocp_resources/virtual_machine_cluster_instance_types.py
  ocp_resources/virtual_machine_cluster_preferences.py
  ocp_resources/virtual_machine_instance_types.py
  ocp_resources/virtual_machine_preferences.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main

#870 test_resources_definitions: take the name from the code
  tests/test_validate_resources.py
Labels: size/XS, Verified, branch-main

#882 code-check add python 3.11
  .github/workflows/code-check.yml
Labels: size/XS, Verified, branch-main

#896 add new exception, as it is recoverable
  ocp_resources/resource.py
Labels: size/XS, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main
