Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-04, with the labels that each got.

#468 Pre commit update modules
  .pre-commit-config.yaml
Labels: size/XS, Verified

#483 Add Failing condition
  ocp_resources/resource.py
Labels: size/XS, Verified

#464 Do not call `_get_port_from_nns` if no self.nodes
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#486 Enable pycln in pre-commit
  .pre-commit-config.yaml
Labels: size/XS, Verified

#491 Update pre-commit
  .pre-commit-config.yaml
Labels: size/XS, Verified

#493 Update pre-commit
  .pre-commit-config.yaml
Labels: size/XS, Verified

#497 pre-commit update
  .pre-commit-config.yaml
Labels: size/XS, Verified

#488 add new resource.Apigroup entries
  ocp_resources/resource.py
Labels: size/XS, Verified

#504 Enter validate_create and wait_for_interface_deleted if self.worker_pods
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, Verified

#499 add wait argument to deploy()
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
Labels: size/XS, size/S, Verified

#508 Add tekton tasks
  ocp_resources/resource.py
  ocp_resources/tekton_tasks.py
Labels: size/XS, Verified
