Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-02, with the labels that each got.

#368 Cherrypick remove nudge delete on namespaces (#74)
  ocp_resources/namespace.py
  ocp_resources/project.py
  ocp_resources/utils.py
Labels: Verified, Ready for merge

#369 TimeoutWatch.remaining_time remove unused arg 'log'
  ocp_resources/utils.py
Labels: Verified, size/XS, Ready for merge

#373 Cherrypick - add DataSource resource
  ocp_resources/data_source.py
  ocp_resources/node_network_state.py
  tests/test_validate_resources.py
Labels: Verified, size/S, Ready for merge

#371 Add job resource for job kind
  ocp_resources/job.py
  ocp_resources/resource.py
Labels: Verified, size/XS, Ready for merge

#410 Remove pin of openshift version
  setup.py
  tox.ini
Labels: size/XS, Verified

#384 Added clean_up to Project
  ocp_resources/project.py
Labels: size/XS, Verified

#395 NodeNetworkConfigurationPolicy - update wait_for_configuration_condit…
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#412 nncp - wait_for_configuration_conditions_unknown_or_progressing - ret…
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#416 nncp - use clean_up, add collect log
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
Labels: size/XS, Verified

#414 nncp - use clean_up, add collect log
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
Labels: size/XS, Verified

#418 nncp - fix clean_up()
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#420 nncp - fix clean_up()
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#376 Add vddk settings in Provider
  ocp_resources/provider.py
Labels: size/XS, Verified

#422 Remove kubernetes from setup.py
  setup.py
Labels: size/XS, Verified

#428 Remove kubernetes and pin openshift to version==0.12.1 setup.py
  setup.py
Labels: size/XS, Verified

#426 Remove kubernetes and pin openshift to version==0.12.1 setup.py
  setup.py
Labels: size/XS, Verified

#432 Update the image stream resource
  ocp_resources/image_stream.py
Labels: size/M, Verified

#433 Add LoadBalancer type - named LOAD_BALANCER
  ocp_resources/service.py
Labels: size/XS, Verified

#437 Backport wait_for_configuration_conditions_unknown_or_progressing
  ocp_resources/node_network_configuration_policy.py
Labels: size/M, Verified

#443 Renamed function from _virsh_cmd to virsh_cmd
  ocp_resources/virtual_machine_instance.py
Labels: size/XS, Verified

#441 nncp - wait_for_status_success - fix log if no node selector
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, Verified
