Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-12, with the labels that each got.

#971 rename all res to self.res
  ocp_resources/backup.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cluster_role.py
  ocp_resources/cluster_role_binding.py
  ocp_resources/configmap.py
  ocp_resources/data_import_cron.py
  ocp_resources/data_source.py
  ocp_resources/datavolume.py
  ocp_resources/hook.py
  ocp_resources/host.py
  ocp_resources/hostpath_provisioner.py
  ocp_resources/hyperconverged.py
  ocp_resources/image_stream.py
  ocp_resources/job.py
  ocp_resources/kube_descheduler.py
  ocp_resources/machine_health_check.py
  ocp_resources/machine_set.py
  ocp_resources/migration.py
  ocp_resources/migration_policy.py
  ocp_resources/namespace.py
  ocp_resources/network_attachment_definition.py
  ocp_resources/network_map.py
  ocp_resources/node_maintenance.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/operator_group.py
  ocp_resources/operator_source.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/plan.py
  ocp_resources/pod_disruption_budget.py
  ocp_resources/priority_class.py
  ocp_resources/provider.py
  ocp_resources/resource.py
  ocp_resources/restore.py
  ocp_resources/role_binding.py
  ocp_resources/route.py
  ocp_resources/secret.py
  ocp_resources/sriov_network.py
  ocp_resources/sriov_network_node_policy.py
  ocp_resources/storage_map.py
  ocp_resources/subscription.py
  ocp_resources/upload_token_request.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance_migration.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/XXL, Verified, Approved-by-rnetser, branch-v4.11

#995 cherry-pick to v4.8: [Storage] fix snapshot resources
  ocp_resources/constants.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/M, Verified, Approved-by-myakove, branch-v4.8

#998 create(): Fix initial_resource_version call
  ocp_resources/resource.py
Labels: size/XS, Verified, branch-main

#1004 Add code examples
  README.md
  examples/general.py
  examples/node_network_configuration_policy.py
  examples/pods.py
  examples/virtual_machine.py
Labels: size/L, Verified, Approved-by-rnetser, branch-main

#1003 Allow templates from all namespaces to be processed
  ocp_resources/template.py
Labels: size/XS, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#990 add retry on exception and timeout_seconds for get call
  ocp_resources/resource.py
Labels: size/S, Verified, Approved-by-myakove, branch-main

#1023 [v4.11] add retry on exception and timeout_seconds for get call
  ocp_resources/constants.py
  ocp_resources/resource.py
Labels: size/S, Verified, Approved-by-rnetser, branch-auto-cherry-pick-add_retry

#988 Add MetalLB and it's resources
  ocp_resources/ip_address_pool.py
  ocp_resources/l2_advertisement.py
  ocp_resources/metallb.py
  ocp_resources/resource.py
Labels: size/L, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#1016 Remove kube_v1_api function
  ocp_resources/pod.py
  ocp_resources/resource.py
Labels: size/XS, Verified, branch-main

#1029 [v4.10] add retry on exception and timeout_seconds for get call (#1023)
  ocp_resources/constants.py
  ocp_resources/resource.py
Labels: size/S, Verified, Approved-by-myakove, branch-v4.10

#1031 Add to_yaml() function
  ocp_resources/resource.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-main

#1027 remove unused files: scripts/release.sh CHANGELOG.md
  CHANGELOG.md
  scripts/release.sh
Labels: size/L, Verified, branch-main

#1039 remove unused files: scripts/release.sh CHANGELOG.md
  CHANGELOG.md
  scripts/release.sh
Labels: size/L, branch-v4.10

#1041 remove unused files: scripts/release.sh CHANGELOG.md
  CHANGELOG.md
  scripts/release.sh
Labels: size/L, branch-v4.9

#1043 remove unused files: scripts/release.sh CHANGELOG.md
  CHANGELOG.md
Labels: size/L, branch-v4.8

#994 Add functionality to role.py and refactor cluster_role.py
  examples/role.py
  ocp_resources/cluster_role.py
  ocp_resources/role.py
Labels: size/L, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#1045 Add MetalLB and it's resources
  ocp_resources/ip_address_pool.py
  ocp_resources/l2_advertisement.py
  ocp_resources/metallb.py
  ocp_resources/resource.py
Labels: size/L, Verified, branch-v4.12

#1018 Add Pipelineruns resource to trigger pipelines with custom params
  ocp_resources/pipelineruns.py
  ocp_resources/resource.py
Labels: size/M, Verified, branch-main
