Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-01, with the labels that each got.

#329 SriovNetwork - allow macspoofchk configuration
  ocp_resources/sriov_network.py
Labels: Verified, size/XS, Ready for merge

#321 handle capture syntax
  README.md
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/S, Ready for merge

#335 NNCP: get NNCE for node
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/XS, Ready for merge

#327 Add storage API to data volume
  ocp_resources/datavolume.py
Labels: Verified, size/XS, Ready for merge

#333 Allow ipv6 config
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/S, Ready for merge

#343 NNCP: return NNCE object and not list
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/XS, Ready for merge

#339 Refactor NNCP
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/M, Ready for merge

#351 NNCP: call to_dict() if not self.res
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
Labels: Verified, size/XS

#354 Add readyReplicas to deployment wait_for_replicas
  ocp_resources/deployment.py
Labels: Verified, size/XS, Ready for merge

#356 Allow ifaces update
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/XS, Ready for merge

#349 Add support to dry_run flag
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cluster_role.py
  ocp_resources/configmap.py
  ocp_resources/data_import_cron.py
  ocp_resources/data_source.py
  ocp_resources/datavolume.py
  ocp_resources/hook.py
  ocp_resources/host.py
  ocp_resources/hostpath_provisioner.py
  ocp_resources/hyperconverged.py
  ocp_resources/kube_descheduler.py
  ocp_resources/machine.py
  ocp_resources/machine_health_check.py
  ocp_resources/machine_set.py
  ocp_resources/migration.py
  ocp_resources/namespace.py
  ocp_resources/network_map.py
  ocp_resources/node_maintenance.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/operator_group.py
  ocp_resources/operator_source.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/plan.py
  ocp_resources/pod.py
  ocp_resources/pod_disruption_budget.py
  ocp_resources/priority_class.py
  ocp_resources/project.py
  ocp_resources/provider.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
  ocp_resources/route.py
  ocp_resources/secret.py
  ocp_resources/sriov_network.py
  ocp_resources/sriov_network_node_policy.py
  ocp_resources/storage_map.py
  ocp_resources/subscription.py
  ocp_resources/upload_token_request.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_instance_migration.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: Verified, size/M

#358 reduce congitive complexity
  ocp_resources/deployment.py
Labels: Verified, size/XS, Ready for merge

#362 nncp: check status unknown before validate
  ocp_resources/node_network_configuration_policy.py
Labels: Verified, size/XS, Ready for merge

#364 allow optional iface teardwon state setting
  ocp_resources/node_network_configuration_policy.py
  tests/test_validate_resources.py
Labels: Verified, size/XS, Ready for merge

#366 Support log to file
  ocp_resources/logger.py
Labels: Verified, size/XS, Ready for merge
