Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-03, with the labels that each got.

#436 Support multiple tags in imagesteam
  ocp_resources/image_stream.py
Labels: size/S, Verified

#449 Allow manipulation of nncp deployment timeout
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#445 Cherrypick nncp status
  ocp_resources/node_network_configuration_policy.py
Labels: size/M, Verified

#453 add registry.redhat.io to Resource.ApiGroup
  ocp_resources/resource.py
Labels: size/XS, Verified

#457 yaml_file: accept .StringIO object
  ocp_resources/resource.py
Labels: size/XS, Verified

#455 success timeout
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#462 Remove deprecated distutils Version, use packaging.version
  ocp_resources/resource.py
  setup.py
Labels: size/XS, Verified

#459 Add new resource: Migration Policy
  ocp_resources/migration_policy.py
  ocp_resources/resource.py
Labels: size/M, Verified

#465 Logger add duplicate filter
  ocp_resources/logger.py
Labels: size/S, Verified
