Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-11, with the labels that each got.

#904 Use one logger from Resource class
  ocp_resources/benchmark.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/data_source.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/machine_set.py
  ocp_resources/mtv.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/route.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/upload_token_request.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/L, Verified, Approved-by-rnetser, branch-main

#910 Use one logger from Resource class
  ocp_resources/benchmark.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/data_source.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/machine_set.py
  ocp_resources/mtv.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/route.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/upload_token_request.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/L, Verified, Approved-by-rnetser, branch-v4.10

#916 Remove vm wait_for_status function
  ocp_resources/virtual_machine.py
Labels: size/S, Verified, Approved-by-myakove, branch-main

#919 Use one logger from Resource class
  ocp_resources/benchmark.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/mtv.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/route.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/upload_token_request.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/L, Verified, Approved-by-rnetser, branch-v4.8

#923 Fix duplicate logs
  ocp_resources/logger.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-main

#937 Fix VM wait_for_status calls
  ocp_resources/virtual_machine.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-main

#921 Cherry pick: Remove vm wait_for_status function (0463e59)
  ocp_resources/virtual_machine.py
Labels: size/S, branch-v4.11

#922 Cherry pick: Remove vm wait_for_status function (0463e59)
  ocp_resources/virtual_machine.py
Labels: size/S, branch-v4.12

#943 create(), remove body args
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-main

#953 create(), remove body args
  ocp_resources/resource.py
Labels: size/XS, Verified, branch-v4.9

#955 create(), remove body args
  ocp_resources/resource.py
Labels: size/XS, Verified, branch-v4.8

#958 Fix the typo in VM status
  ocp_resources/virtual_machine.py
Labels: size/XS, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#935 nad: add support for linux-bridge and ovs
  ocp_resources/network_attachment_definition.py
Labels: size/L, Verified, branch-main

#963 Fix the typo in VM status
  ocp_resources/virtual_machine.py
Labels: size/XS, Verified, Approved-by-myakove, branch-v4.11

#960 Node Health Check was incorrectly mentioned as namespace dependent in documentation.
  ocp_resources/node_health_check.py
Labels: size/XS, Verified, branch-main

#959 Added resource scheduler. This is a cluster wide resource.
  ocp_resources/scheduler.py
Labels: size/XS, Verified, branch-main

#968 Node Health Check was incorrectly mentioned as namespace dependent in documentation. (#960)
  ocp_resources/node_health_check.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-v4.12

#967 Added resource scheduler. This is a cluster wide resource. (#959)
  ocp_resources/scheduler.py
Labels: size/XS, branch-v4.12

#913 cherry-pick to V4.9: Storage: fix snapshot resources
  ocp_resources/constants.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/M, Verified, Approved-by-myakove, branch-v4.9

#945 rename all res to self.res
  ocp_resources/backup.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cluster_role.py
  ocp_resources/cluster_role_binding.py
  ocp_resources/configmap.py
  ocp_resources/data_import_cron.py
  ocp_resources/data_source.py
  ocp_resources/datavolume.py
  ocp_resources/hook.py
  ocp_resources/host.py
  ocp_resources/hostpath_provisioner.py
  ocp_resources/hyperconverged.py
  ocp_resources/image_stream.py
  ocp_resources/job.py
  ocp_resources/kube_descheduler.py
  ocp_resources/machine_health_check.py
  ocp_resources/machine_set.py
  ocp_resources/migration.py
  ocp_resources/migration_policy.py
  ocp_resources/namespace.py
  ocp_resources/network_attachment_definition.py
  ocp_resources/network_map.py
  ocp_resources/node_maintenance.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/operator_group.py
  ocp_resources/operator_source.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/plan.py
  ocp_resources/pod_disruption_budget.py
  ocp_resources/priority_class.py
  ocp_resources/provider.py
  ocp_resources/resource.py
  ocp_resources/restore.py
  ocp_resources/role_binding.py
  ocp_resources/route.py
  ocp_resources/secret.py
  ocp_resources/sriov_network.py
  ocp_resources/sriov_network_node_policy.py
  ocp_resources/storage_map.py
  ocp_resources/subscription.py
  ocp_resources/upload_token_request.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_export.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance_migration.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/XXL, Verified, Approved-by-rnetser, branch-main

#969 Rename all res to self.res to be consistent with the code.
  ocp_resources/backup.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cluster_role.py
  ocp_resources/cluster_role_binding.py
  ocp_resources/configmap.py
  ocp_resources/data_import_cron.py
  ocp_resources/data_source.py
  ocp_resources/datavolume.py
  ocp_resources/hook.py
  ocp_resources/host.py
  ocp_resources/hostpath_provisioner.py
  ocp_resources/hyperconverged.py
  ocp_resources/image_stream.py
  ocp_resources/job.py
  ocp_resources/kube_descheduler.py
  ocp_resources/machine_health_check.py
  ocp_resources/machine_set.py
  ocp_resources/migration.py
  ocp_resources/migration_policy.py
  ocp_resources/namespace.py
  ocp_resources/network_attachment_definition.py
  ocp_resources/network_map.py
  ocp_resources/node_maintenance.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/operator_group.py
  ocp_resources/operator_source.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/plan.py
  ocp_resources/pod_disruption_budget.py
  ocp_resources/priority_class.py
  ocp_resources/provider.py
  ocp_resources/resource.py
  ocp_resources/restore.py
  ocp_resources/role_binding.py
  ocp_resources/route.py
  ocp_resources/secret.py
  ocp_resources/sriov_network.py
  ocp_resources/sriov_network_node_policy.py
  ocp_resources/storage_map.py
  ocp_resources/subscription.py
  ocp_resources/upload_token_request.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_export.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance_migration.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/XXL, branch-v4.12

#973 [v4.10] Fix the typo in VM status
  ocp_resources/virtual_machine.py
Labels: size/XS, Verified, Approved-by-myakove, branch-v4.10

#975 [v4.9] Fix the typo in VM status (#958)
  ocp_resources/virtual_machine.py
Labels: size/XS, Verified, Approved-by-myakove, branch-v4.9

#978 Add controller revision resource
  ocp_resources/controller_revision.py
Labels: size/S, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#979 Adding CONTRIBUTING.md file
  CONTRIBUTING.md
  ocp_resources/image_stream.py
Labels: size/M, Verified, Approved-by-myakove, branch-main, Approved-by-dbasunag

#826 watcher function to watch the resource using Kubernetes watch api.
  ocp_resources/resource.py
Labels: size/M, Verified

#986 Fix skip_existing_resource_creation_teardown to_dict call
  ocp_resources/utils.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-main
