Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-06, with the labels that each got.

#601 Revert "Move kube_v1_api init to pod.execute"
  ocp_resources/pod.py
Labels: size/XS, Verified

#608 Add Failing condition (#483)
  ocp_resources/resource.py
Labels: size/XS, Verified

#607 Add VirtualMachineFlavor resource
  ocp_resources/virtual_machine_flavor.py
Labels: size/XS, Verified

#610 Support reuse of already existing resource
  ocp_resources/resource.py
  ocp_resources/utils.py
Labels: size/L, Verified

#614 Merge pull request #610 from myakove/reuse-existing-resources
  ocp_resources/resource.py
  ocp_resources/utils.py
Labels: size/L, Verified

#616 Secret - add secret type
  ocp_resources/secret.py
Labels: size/XS, Verified

#618 Secret - add type
  ocp_resources/secret.py
Labels: size/XS, Verified

#620 Add VirtualMachineClusterFlavor resource
  ocp_resources/virtual_machine_cluster_flavor.py
  ocp_resources/virtual_machine_flavor.py
Labels: size/XS, Verified

#623 ConfigMap: data is optional
  ocp_resources/configmap.py
  ocp_resources/resource.py
  ocp_resources/tekton_tasks.py
  tests/test_validate_resources.py
Labels: size/XS, Verified

#621 _base_body - save yaml_file_contents
  ocp_resources/resource.py
Labels: size/S, Verified

#631 code-check: Add python 3.10
  .github/workflows/code-check.yml
Labels: size/XS, Verified

#612 Allow creating jobs
  ocp_resources/job.py
Labels: size/M, Verified

#643 code-check: Add python 3.10 (#631)
  .github/workflows/code-check.yml
Labels: size/XS, Verified

#645 pre-commit: add detect-secrets plugin
  .pre-commit-config.yaml
  ocp_resources/virtual_machine_import.py
Labels: size/XS, Verified

#637 Move reuse resource and skip teardown to deploy/clean_up
  ocp_resources/resource.py
Labels: size/S, Verified

#651 Add DATA_IMPORT_CRON_TEMPLATE_KUBEVIRT_IO to resources.apiGroup
  ocp_resources/resource.py
Labels: size/XS, Verified

#657 Resource additions for standalone k8s-nmstate.
  ocp_resources/catalog_source.py
  ocp_resources/nmstate.py
Labels: size/S, Verified

#665 Resource status - add Error
  ocp_resources/resource.py
Labels: size/XS, Verified
