Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-05, with the labels that each got.

#517 nncp - change 'status' to propety
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#518 Add CSIDriver Resource
  ocp_resources/csidriver.py
Labels: size/XS, Verified

#522 Add CSIDriver Resource
  ocp_resources/csidriver.py
Labels: size/XS, Verified

#506 Allow manipulting timeout for vmi deletion when stopping VM
  ocp_resources/virtual_machine.py
Labels: size/XS, Verified

#520 nncp - change 'status' to propety
  ocp_resources/node_network_configuration_policy.py
Labels: size/M, size/XS, Verified

#523 update TimeoutSampler call using self.status
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#525 update TimeoutSampler call using self.status (#523)
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, Verified

#531 Add wait for deploy()
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
Labels: size/XS, Verified

#533 add two entries to ApiGroup
  ocp_resources/resource.py
Labels: size/XS, Verified

#514 Allow creating ClusterRoleBinding with parameters, and adding rules to ClusterRoles
  ocp_resources/cluster_role.py
  ocp_resources/cluster_role_binding.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
Labels: size/M, Verified

#535 Allow creating ClusterRoleBinding with parameters, and adding rules to ClusterRoles
  CHANGELOG.md
  ocp_resources/cluster_role.py
  ocp_resources/cluster_role_binding.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
Labels: size/M, Verified

#539 README - update release process
  .gitignore
  README.md
Labels: size/S, Verified

#541 README - update release process
  .gitignore
  README.md
Labels: size/S, Verified

#545 README - update release process
  .gitignore
  README.md
Labels: size/S, Verified

#543 README - update release process
  .gitignore
  README.md
Labels: size/S, Verified

#547 README - update release process
  .gitignore
  README.md
Labels: size/M, Verified

#549 README - update release process
  .gitignore
  README.md
Labels: size/M, Verified

#551 Add new resource console_plugin
  ocp_resources/console_plugin.py
Labels: size/XS, Verified

#553 Add new resource console_plugin (#551)
  ocp_resources/console_plugin.py
Labels: size/XS

#555 ChaosEngine: set constants uppercase
  ocp_resources/chaos_engine.py
Labels: size/XS, Verified

#557 ChaosEngine: set constants uppercase (#555)
  ocp_resources/chaos_engine.py
Labels: size/XS

#559 ChaosEngine: set constants uppercase (#555)
  ocp_resources/chaos_engine.py
Labels: size/XS

#561 Move kube_v1_api init to pod.execute
  ocp_resources/pod.py
Labels: size/XS, Verified

#580 Move kube_v1_api init to pod.execute (#561)
  ocp_resources/pod.py
Labels: size/XS, Verified

#565 Add **kwargs to ClusterRoleBinding __init__
  ocp_resources/cluster_role_binding.py
Labels: size/XS, Verified

#585 Add **kwargs to ClusterRoleBinding __init__ (#565)
  ocp_resources/cluster_role_binding.py
Labels: size/XS, Verified

#588 Add **kwargs to ClusterRoleBinding __init__ (#565)
  ocp_resources/cluster_role_binding.py
Labels: size/XS, Verified

#582 ChaosResult resource
  ocp_resources/chaos_result.py
Labels: size/XS, Verified

#593 ChaosResult resource (#582)
  ocp_resources/chaos_result.py
Labels: size/XS, Verified

#595 ChaosResult resource (#582)
  ocp_resources/chaos_result.py
Labels: size/XS, Verified

#599 [4.8] Check existence of worker-pods member in NNCP object to avoid none-object failure
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, Verified
