Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-07, with the labels that each got.

#669 Deployment - update wait_for_replicas
  ocp_resources/deployment.py
Labels: size/XS, Verified

#677 Move reuse resource and skip teardown to deploy/clean_up (#637)
  ocp_resources/resource.py
  ocp_resources/utils.py
Labels: size/L, Verified

#691 Resource additions for standalone k8s-nmstate. (#657)
  ocp_resources/catalog_source.py
  ocp_resources/nmstate.py
Labels: size/S, Verified

#695 Add microsecond precision to log
  ocp_resources/logger.py
Labels: size/XS, Verified

#697 Fix for unsafe repository action error
  .github/workflows/create-auto-pr-for-merge-pr-in-main.yml
Labels: size/XS

#710 Raise ExecOnPodError on 'Failure' in pod.execute
  ocp_resources/pod.py
Labels: size/XS, Verified

#723 Add MachineConfig resource
  ocp_resources/machine_config.py
Labels: size/XS, Verified

#727 flavors rename to instance types and preference added
  ocp_resources/resource.py
  ocp_resources/virtual_machine_cluster_flavor.py
  ocp_resources/virtual_machine_cluster_instance_types.py
  ocp_resources/virtual_machine_cluster_preferences.py
  ocp_resources/virtual_machine_flavor.py
  ocp_resources/virtual_machine_instance_types.py
  ocp_resources/virtual_machine_preferences.py
Labels: size/S, Verified

#662 Remove saphana from template
  ocp_resources/template.py
Labels: size/XS, Verified

#722 Add NodeHealthCheck api
  ocp_resources/node_health_check.py
  ocp_resources/resource.py
Labels: size/XS, Verified

#705 [4.9] Add microsecond precision to log (#695)
  ocp_resources/benchmark.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/event.py
  ocp_resources/logger.py
  ocp_resources/machine_set.py
  ocp_resources/mtv.py
  ocp_resources/namespace.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/route.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/upload_token_request.py
  ocp_resources/utils.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
  setup.py
Labels: size/L, Verified
