Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2022-08, with the labels that each got.

#706 [4.8] Add microsecond precision to log (#695)
  ocp_resources/benchmark.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/event.py
  ocp_resources/logger.py
  ocp_resources/mtv.py
  ocp_resources/namespace.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/route.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/upload_token_request.py
  ocp_resources/utils.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
  setup.py
Labels: size/L, Verified

#733 Remove all collect data functions
  ocp_resources/resource.py
Labels: size/M, Verified

#721 Add backup restore
  ocp_resources/backup.py
  ocp_resources/resource.py
  ocp_resources/restore.py
Labels: size/L, Verified

#728 Add NodeHealthCheck api (#722)
  ocp_resources/node_health_check.py
  ocp_resources/resource.py
Labels: size/XS, Verified

#741 Move the return code check in pod.exec to be after ignore_rc check
  ocp_resources/pod.py
Labels: size/XS, Verified

#750 pre-commit update
  .flake8
  .pre-commit-config.yaml
Labels: Verified

#754 pre-commit update (#750) (#752)
  .flake8
  .pre-commit-config.yaml
  ocp_resources/virtual_machine_import.py
Labels: size/S, Verified

#731 Do not require live cluster only for create class instance
  ocp_resources/resource.py
Labels: size/S, Verified

#762 Do not require live cluster only for create class instance (#731) (#760)
  ocp_resources/resource.py
Labels: size/L, Verified

#764 get_client - support kubeconfig dict
  ocp_resources/resource.py
Labels: size/S, Verified

#770 updates to pod to use kube_v1_api
  ocp_resources/pod.py
Labels: size/XS, Verified, Reviewed By myakove

#751 add prometheus resource
  ocp_resources/prometheus.py
Labels: size/XS, Verified

#774 pod.node: Raise if pod is not running
  ocp_resources/pod.py
Labels: size/XS, Verified, Reviewed By rnetser

#776 add events for resources
  ocp_resources/event.py
  ocp_resources/resource.py
  tests/test_validate_resources.py
Labels: size/L, Verified

#784 Get all cluster resources function
  ocp_resources/resource.py
Labels: size/S, Verified, Reviewed By rnetser

#788 Add "ImagePullBackOff" and "ErrImagePull" pod statuses
  ocp_resources/pod.py
Labels: size/XS, Verified, Reviewed By myakove, Reviewed By rnetser, Reviewed-By-rnetser

#692 Storage: fix snapshot resources
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/M, Verified
