Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-02, with the labels that each got.

#1077 OCSInitialization resource from the ocs.openshift.io API group
  ocp_resources/ocs_initialization.py
  ocp_resources/resource.py
Labels: size/M, Verified, Approved-by-myakove, Approved-by-rnetser, Changes_Requested-by-rnetser, Commented-by-rnetser, branch-main

#1097 [v4.11] Fix skip_existing_resource_creation_teardown to_dict call
  ocp_resources/utils.py
Labels: size/XS, Verified, Approved-by-myakove, branch-v4.11

#1096 When non-root virt-launcher: Switch to virtqemud if machine type has rhel9 and
  ocp_resources/virtual_machine_instance.py
Labels: size/S, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#1100 Adding hypervisor connection uri based on the socket present in virt-launcher pod (#1096)
  ocp_resources/virtual_machine_instance.py
Labels: size/S, Verified, Approved-by-myakove, branch-v4.12

#1114 Pre commit update hooks
  .pre-commit-config.yaml
  ocp_resources/chaos_engine.py
  ocp_resources/migration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/ocs_initialization.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
Labels: size/XS, branch-main

#1112 Update pre-commit hooks
  .pre-commit-config.yaml
  ocp_resources/chaos_engine.py
  ocp_resources/migration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
Labels: size/XS, branch-v4.13

#1110 Update pre-commit hooks
  .pre-commit-config.yaml
  ocp_resources/chaos_engine.py
  ocp_resources/migration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
Labels: size/XS, branch-v4.12

#1108 Update pre-commit hooks
  .pre-commit-config.yaml
  ocp_resources/chaos_engine.py
  ocp_resources/migration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
Labels: size/XS, branch-v4.11

#1106 Update pre-commit hooks
  .pre-commit-config.yaml
  ocp_resources/chaos_engine.py
  ocp_resources/cluster_role.py
  ocp_resources/migration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
Labels: size/XS, branch-v4.10

#1104 Update pre-commit hooks
  .pre-commit-config.yaml
  ocp_resources/chaos_engine.py
  ocp_resources/node_network_state.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
Labels: size/XS, branch-v4.9

#1102 Update pre-commit hooks
  .pre-commit-config.yaml
  ocp_resources/chaos_engine.py
  ocp_resources/node_network_state.py
  ocp_resources/resource.py
  ocp_resources/role_binding.py
Labels: size/XS, branch-v4.8

#1118 Fix role example
  examples/role.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main

#1119 Refactor role example
  examples/role.py
Labels: size/S, Verified, Approved-by-myakove, branch-v4.12

#1116 Convert setup.py/cfg to pyproject.toml
  .release-it.json
  VERSION
  pyproject.toml
  setup.cfg
  setup.py
Labels: size/M, Verified, branch-main

#1122 Convert setup.py/cfg to pyproject.toml (#1116)
  .release-it.json
  VERSION
  pyproject.toml
  setup.cfg
  setup.py
Labels: size/M, Verified, branch-v4.13

#1124 Convert setup.py/cfg to pyproject.toml (#1116) (#1122)
  .release-it.json
  VERSION
  pyproject.toml
  setup.cfg
  setup.py
Labels: size/M, branch-v4.12

#1128 Convert setup.py/cfg to pyproject.toml (#1116) (#1122)
  .release-it.json
  VERSION
  pyproject.toml
  setup.cfg
  setup.py
Labels: size/M, branch-v4.10

#1126 Use pyproject.toml v4.11
  .release-it.json
  VERSION
  pyproject.toml
  setup.cfg
  setup.py
Labels: size/M, branch-v4.11

#1132 Convert setup.py/cfg to pyproject.toml (#1116) (#1122)
  .release-it.json
  VERSION
  pyproject.toml
  setup.cfg
  setup.py
Labels: size/M, branch-v4.8

#1130 Convert setup.py/cfg to pyproject.toml (#1116) (#1122)
  .release-it.json
  VERSION
  pyproject.toml
  setup.cfg
  setup.py
Labels: size/M, branch-v4.9

#1134 Temporary in-solidarity ignore for grafana api docs
  .github/in-solidarity.yml
Labels: size/XS, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main
