Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-03, with the labels that each got.

#1136 Add stale configuration
  .github/stale.yml
Labels: size/XS, Verified, Approved-by-rnetser, branch-main

#1101 Refactor job resource
  ocp_resources/daemonset.py
  ocp_resources/job.py
Labels: size/S, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#1138 Reformat black and isort
  .isort.cfg
  .pre-commit-config.yaml
  docs/conf.py
  examples/general.py
  examples/node_network_configuration_policy.py
  examples/pods.py
  examples/role.py
  examples/virtual_machine.py
  ocp_resources/constants.py
  ocp_resources/event.py
  ocp_resources/logger.py
  ocp_resources/machine_set.py
  ocp_resources/network_attachment_definition.py
  ocp_resources/node_network_state.py
  ocp_resources/resource.py
  ocp_resources/utils.py
  pyproject.toml
Labels: size/S, Verified, Approved-by-rnetser, branch-main

#1144 Add operator resource
  ocp_resources/operator.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-main

#1151 Adding new fields selector.matchLabels.pvLabel under spec of pvc
  ocp_resources/persistent_volume_claim.py
Labels: size/XS, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main, verified'

#1152 TimeoutSampler - update docstring
  ocp_resources/utils.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main

#1166 Adding a new status constant ERROR_UNSCHEDULABLE under vm status
  ocp_resources/virtual_machine.py
Labels: size/XS, branch-main

#1169 release-it: read version from VERSION file
  .gitignore
  .release-it.json
  README.md
Labels: size/XS, Verified, branch-main

#1181 Use logger from python-simple-logger
  ocp_resources/event.py
  ocp_resources/logger.py
  ocp_resources/resource.py
  ocp_resources/utils.py
  pyproject.toml
Labels: size/M, Verified, Approved-by-rnetser, branch-main

#1183 Use logger from python-simple-logger (#1181)
  ocp_resources/event.py
  ocp_resources/logger.py
  ocp_resources/resource.py
  ocp_resources/utils.py
  pyproject.toml
Labels: size/M, Verified, branch-v4.13
