Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-11, with the labels that each got.

#1488 Update csi_storage_capacity class constructor and documentation
  ocp_resources/csi_storage_capacity.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser

#1526 pre-commit: remove FCN checl
  .flake8
  .pre-commit-config.yaml
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#1524 Pre commit use ruff 4.14
  .flake8
  .pre-commit-config.yaml
  examples/special_cases.py
  ocp_resources/catalog_source.py
  ocp_resources/catalog_source_config.py
  ocp_resources/cdi_config.py
  ocp_resources/cluster_role_binding.py
  ocp_resources/controller_revision.py
  ocp_resources/cron_job.py
  ocp_resources/csi_storage_capacity.py
  ocp_resources/daemonset.py
  ocp_resources/data_import_cron.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/endpoint_slice.py
  ocp_resources/endpoints.py
  ocp_resources/event.py
  ocp_resources/hyperconverged.py
  ocp_resources/image_content_source_policy.py
  ocp_resources/ip_address_pool.py
  ocp_resources/job.py
  ocp_resources/l2_advertisement.py
  ocp_resources/machine.py
  ocp_resources/machine_health_check.py
  ocp_resources/machine_set.py
  ocp_resources/migration.py
  ocp_resources/migration_policy.py
  ocp_resources/mtv.py
  ocp_resources/multi_cluster_observability.py
  ocp_resources/network_attachment_definition.py
  ocp_resources/node.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/persistent_volume.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/pipeline.py
  ocp_resources/pipelineruns.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/route.py
  ocp_resources/secret.py
  ocp_resources/sriov_network_node_policy.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/storage_class.py
  ocp_resources/subscription.py
  ocp_resources/task_run.py
  ocp_resources/template.py
  ocp_resources/utils.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_clone.py
  ocp_resources/virtual_machine_export.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
  pyproject.toml
  tests/test_resources.py
  tests/test_validate_resources.py
  tests/unittests/test_utils.py
Labels: size/XXL, verified, can-be-merged, branch-v4.14, approved-rnetser

#1522 Pre commit use ruff 4.15
  .flake8
  .pre-commit-config.yaml
  examples/special_cases.py
  ocp_resources/catalog_source.py
  ocp_resources/cdi_config.py
  ocp_resources/cluster_role_binding.py
  ocp_resources/controller_revision.py
  ocp_resources/cron_job.py
  ocp_resources/csi_storage_capacity.py
  ocp_resources/daemonset.py
  ocp_resources/data_import_cron.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/endpoint_slice.py
  ocp_resources/endpoints.py
  ocp_resources/event.py
  ocp_resources/hyperconverged.py
  ocp_resources/image_content_source_policy.py
  ocp_resources/ip_address_pool.py
  ocp_resources/job.py
  ocp_resources/l2_advertisement.py
  ocp_resources/machine.py
  ocp_resources/machine_health_check.py
  ocp_resources/machine_set.py
  ocp_resources/migration.py
  ocp_resources/migration_policy.py
  ocp_resources/mtv.py
  ocp_resources/multi_cluster_observability.py
  ocp_resources/network_attachment_definition.py
  ocp_resources/node.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/persistent_volume.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/pipeline.py
  ocp_resources/pipelineruns.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/route.py
  ocp_resources/secret.py
  ocp_resources/sriov_network_node_policy.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/storage_class.py
  ocp_resources/subscription.py
  ocp_resources/task_run.py
  ocp_resources/template.py
  ocp_resources/utils.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_clone.py
  ocp_resources/virtual_machine_export.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
  pyproject.toml
  tests/test_resources.py
  tests/test_validate_resources.py
  tests/unittests/test_utils.py
Labels: size/XXL, verified, can-be-merged, branch-v4.15, approved-rnetser
