Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-09, with the labels that each got.

#1369 Added support for tekton taskrun (#1365)
  ocp_resources/task_run.py
Labels: size/M, verified, can-be-merged, branch-v4.14, ApprovedBy-myakove

#1366 fix wait_until_running() call if vmi object doesn't exist
  ocp_resources/virtual_machine_instance.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14, cherry-pick-v4.13

#1398 renovate: use only 2 last branches
  renovate.json
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#1401 Wait for resource exists before sampling for condition
  ocp_resources/deployment.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/utils.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/L, verified, branch-main, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.14, cherry-pick-v4.13

#1404 Wait for resource exists before sampling for condition (#1401) (#1403)
  ocp_resources/deployment.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/resource.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/utils.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/L, verified, branch-v4.13, can-be-merged, ApprovedBy-rnetser

#1407 create(): add AttributeError to contextlib.suppress
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.14, cherry-pick-v4.13

#1406 Update scratch pvc name
  ocp_resources/datavolume.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-rnetser, ApprovedBy-myakove

#1426 Log wait_timeout and elapsed_time in human readable time
  ocp_resources/utils.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.14, cherry-pick-v4.13

#1415 Removed 'catalog_source_config' resource
  ocp_resources/catalog_source_config.py
Labels: size/M, verified, branch-main, can-be-merged, ApprovedBy-myakove

#1430 Fix calling retry_cluster_exceptions when reurn None
  ocp_resources/resource.py
Labels: size/S, verified, branch-main, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.14, cherry-pick-v4.13

#1434 add use_populator property to PVC
  ocp_resources/datavolume.py
  ocp_resources/persistent_volume_claim.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-myakove, ApprovedBy-jpeimer

#1441 Poetry use kubernetes 28.1.0b1
  poetry.lock
  pyproject.toml
Labels: size/M, verified, branch-main, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.15

#1417 Fix documentation for cluster_role class resource
  ocp_resources/cluster_role.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#1422 Update configmap class constructor and documentation
  ocp_resources/configmap.py
Labels: size/S, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#1419 Update cluster_role_binding class constructor, documentation and add 'to_dict' parameters validation
  ocp_resources/cluster_role_binding.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#1454 Update cron_job class constructor and documentation
  ocp_resources/cron_job.py
Labels: size/S, verified, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14, cherry-pick-v4.15

#1412 Update catalog_source class constructor, documentation and add 'to_dict' parameters validation
  ocp_resources/catalog_source.py
Labels: needs-rebase, size/S, verified, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14, cherry-pick-v4.15

#1463 add MultiClusterHub
  ocp_resources/multi_cluster_hub.py
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14, cherry-pick-v4.15

#1465 Add managedcluster v4.14
  ocp_resources/managed_cluster.py
  ocp_resources/resource.py
Labels: size/XS, verified, can-be-merged, branch-v4.14, ApprovedBy-myakove

#1472 Add prime pvc property
  ocp_resources/datavolume.py
  ocp_resources/persistent_volume_claim.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#1485 Secret - add `stringData` to `keys_to_hash`
  ocp_resources/secret.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14, ApprovedBy-omrirh, cherry-pick-v4.15

#1481 Multi cluster observability
  ocp_resources/multi_cluster_observability.py
  ocp_resources/resource.py
Labels: needs-rebase, size/M, verified, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14, cherry-pick-v4.15
