Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-06, with the labels that each got.

#1237 cherry-pick for add_resource_dns (#1189)
  ocp_resources/dns.py
Labels: size/XS, Verified, Approved-by-myakove, branch-v4.13, can-be-merged

#1238 Refactor node_network_configuration_policy resource (#1202)
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, Verified, Approved-by-myakove, branch-v4.13, can-be-merged

#1240 CP - Refactor node_network_configuration_policy resource (#1202)
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, Verified, Approved-by-myakove, Approved-by-rnetser, branch-v4.12, Approved-by-omrirh, can-be-merged

#1241 Update OWNERS
  OWNERS
Labels: size/XS, Approved-by-myakove, branch-main

#1243 Refactor the code according to flake8 errors (#1205)
  ocp_resources/node.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-v4.11, Approved-by-omrirh, can-be-merged

#1244 [411] CP 1240 refactor node network configuration policy resources
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, Verified, Approved-by-myakove, branch-v4.11, can-be-merged
