Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-04, with the labels that each got.

#1192 Add label parameter to Resource object
  ocp_resources/namespace.py
  ocp_resources/resource.py
Labels: size/XS, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main, Approved-by-omrirh

#1195 Add RHMI custom resource
  .github/in-solidarity.yml
  ocp_resources/resource.py
  ocp_resources/rhmi.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main, Approved-by-omrirh

#1197 Add RHMI custom resource
  .github/in-solidarity.yml
  ocp_resources/resource.py
  ocp_resources/rhmi.py
Labels: size/XS, Verified, branch-v4.13

#1201 manual-cherry-pick: [v4.13] Add label parameter to Resource object
  ocp_resources/namespace.py
  ocp_resources/resource.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-v4.13
