Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-05, with the labels that each got.

#1205 Refactor the code according to flake8 errors
  ocp_resources/node.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main

#1189 Add dns resource
  ocp_resources/dns.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main

#1206 README: Add reference to the project contribution guide
  README.md
Labels: size/XS, Verified, Approved-by-myakove, branch-main

#1202 Refactor node_network_configuration_policy resource
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#1191 add multiple resources
  ocp_resources/cron_job.py
  ocp_resources/csi_storage_capacity.py
  ocp_resources/endpoint_slice.py
  ocp_resources/lease.py
  ocp_resources/pod_metrics.py
  ocp_resources/resource.py
Labels: size/XL, Verified, Approved-by-myakove, branch-main

#1211 Allow ICSP resource creation
  ocp_resources/image_content_source_policy.py
Labels: size/S, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#1215 Support different API groups for resources with the same kind
  examples/special_cases.py
  ocp_resources/resource.py
Labels: size/XS, Verified, Approved-by-myakove, branch-main

#1223 Introduce pipeline resource from tekton (#1188)
  ocp_resources/pipeline.py
Labels: Verified, Approved-by-myakove

#1222 Hash sensitive data in resource logs
  ocp_resources/resource.py
  ocp_resources/secret.py
  pyproject.toml
Labels: size/M, Verified, Approved-by-myakove, Approved-by-rnetser

#1228 Omit secret data - cherry-pick 4.12
  ocp_resources/resource.py
  ocp_resources/secret.py
  pyproject.toml
Labels: size/M, Approved-by-myakove, branch-v4.12

#1204 Exapnd MachineConfigPool for creation
  ocp_resources/machine_config_pool.py
Labels: needs-rebase, size/M, Verified, branch-main

#1231 ICSP: set repository_digest_mirrors to None
  ocp_resources/image_content_source_policy.py
Labels: size/XS, Verified, branch-main, target-version-v4.14
