Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-08, with the labels that each got.

#1330 Add a flat l2 topology NAD option
  ocp_resources/network_attachment_definition.py
Labels: size/S, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#1349 Update Backup and ClusterRole constructors and to_dict function
  ocp_resources/backup.py
  ocp_resources/cluster_role.py
Labels: size/M, verified, branch-main, can-be-merged, ApprovedBy-rnetser

#1352 add more logging to vmi.wait_until_running()
  ocp_resources/virtual_machine_instance.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14

#1356 [4.14] Add an OVN overlay (flat l2 topology) NAD option (#1330)
  ocp_resources/network_attachment_definition.py
Labels: size/S, verified, can-be-merged, branch-v4.14, ApprovedBy-rnetser, ApprovedBy-omrirh

#1361 Add retry to namespace instance
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.14, cherry-pick-v4.13

#1363 Add VM error statuses to VM.Status
  ocp_resources/virtual_machine.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14

#1370 Resource.get - add option to pass exceptions_dict
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-myakove, cherry-pick-v4.14, cherry-pick-v4.13

#1367 Vmi log statuses
  ocp_resources/resource.py
  ocp_resources/virtual_machine_instance.py
Labels: size/S, verified, branch-main, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.14, cherry-pick-v4.13

#1377 Vmi log statuses (#1367) (#1374)
  ocp_resources/resource.py
  ocp_resources/virtual_machine_instance.py
Labels: size/S, verified, branch-v4.13

#1379 TimeoutSampler: always raise TimeoutExpiredError
  ocp_resources/utils.py
  tests/unittests/test_utils.py
Labels: size/XS, verified, branch-main, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.14, cherry-pick-v4.13

#1385 create(): switch to contextlib.suppress(TimeoutExpiredError) (#1383)
  ocp_resources/resource.py
Labels: size/S, branch-v4.14, cherry-pick-v4.13
