Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-07, with the labels that each got.

#1246 StorageClass - add support for resource creation
  ocp_resources/storage_class.py
Labels: size/M, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main, can-be-merged

#1248 wait_for_condition: use sampler, not watcher
  ocp_resources/resource.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-main, can-be-merged

#1250 wait_for_condition: use sampler, not watcher
  ocp_resources/resource.py
Labels: size/XS, Verified, branch-v4.14

#1253 Sync from main
  .github/stale.yml
  .github/workflows/close-stale-issues.yml
  .pre-commit-config.yaml
  OWNERS
  ocp_resources/machine_config_pool.py
  ocp_resources/storage_class.py
  renovate.json
Labels: size/L, Verified, Approved-by-rnetser, can-be-merged, branch-v4.14

#1247 wait_for_dv_success: adapt to Populators, add stop_status_func optional arg
  ocp_resources/constants.py
  ocp_resources/datavolume.py
Labels: size/M, Verified, Approved-by-rnetser, branch-main, can-be-merged

#1257 Add kubevirt market to test_vm
  tests/test_resources.py
  tox.ini
Labels: size/XS, Verified, Approved-by-rnetser, branch-main, can-be-merged

#1261 Revert "Tests add marker v4.14"
  VERSION
Labels: size/XS, branch-main

#1267 cherry-pick: [v4.13] Add kubevirt market to test_vm
  tests/test_resources.py
  tox.ini
Labels: size/XS, Verified, branch-v4.13, cherry-pick, target-branch-v4.12

#1275 Fix pre-commit errors
  ocp_resources/node.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/XS, Verified, branch-v4.10

#1281 Add kubevirt market to test_vm (#1257) (#1265) (#1267) (#1273) (#1277)
  tests/test_resources.py
  tox.ini
Labels: size/XS, branch-v4.8

#1284 Use poetry as build backend
  poetry.lock
  pyproject.toml
Labels: size/XXL, Verified, Approved-by-rnetser, branch-main

#1288 Remove openshift dependencies
  README.md
  ocp_resources/constants.py
  ocp_resources/data_source.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
  poetry.lock
  pyproject.toml
  tests/test_resources.py
  tox.ini
Labels: size/L, Verified, branch-main, can-be-merged, ApprovedBy-rnetser

#1294 Use poetry as build backend (#1284) (#1286) (#1290)
  poetry.lock
  pyproject.toml
Labels: size/XXL, Verified, branch-v4.12, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.11

#1296 Use poetry as build backend (#1284) (#1286) (#1290) (#1294)
  poetry.lock
  pyproject.toml
Labels: size/XXL, Verified, branch-v4.11, can-be-merged, ApprovedBy-rnetser, cherry-pick-v4.10

#1310 Update poetry to fix tomlkit issue (#1306)
  poetry.lock
  pyproject.toml
  tox.ini
Labels: size/L, Verified, branch-v4.14, cherry-pick-v4.13

#1312 Poetry update fix tomlkit v4.14 v4.13
  poetry.lock
  pyproject.toml
  tox.ini
Labels: size/L, Verified, branch-v4.13, cherry-pick-v4.12

#1322 Poetry update fix tomlkit v4.14 v4.13 (#1312) (#1314) (#1316) (#1318)…
  poetry.lock
  pyproject.toml
  tox.ini
Labels: size/L, Verified, branch-v4.8
