Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-12, with the labels that each got.

#1535 test_validate_resources: fix deprecate code
  tests/test_validate_resources.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#1490 Update DataImportCron class constructor, documentation and add 'to_dict' parameters validation
  ocp_resources/data_import_cron.py
Labels: size/M, verified, branch-main, can-be-merged, Stale, approved-myakove

#1537 Add ImageDigestMirrorSet resource to interact with idms resource in a…
  ocp_resources/image_digest_mirror_set.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#1531 Add Managed-Tenant-Quota resources
  ocp_resources/mtq.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine_migration_resource_quota.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove

#1547 Add annotation to StorageClass.Annotations
  ocp_resources/resource.py
  ocp_resources/storage_class.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#1553 TimeoutSampler: add deprecated warn
  .flake8
  ocp_resources/utils.py
Labels: size/XS, verified, can-be-merged, branch-v4.15, approved-rnetser

#1551 User timeout-sampler module
  ocp_resources/benchmark.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/machine_set.py
  ocp_resources/mtv.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/utils.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
  poetry.lock
  pyproject.toml
  tests/unittests/test_utils.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser

#1515 Add ResourceQuota and LimitRange objects
  ocp_resources/limit_range.py
  ocp_resources/resource_quota.py
Labels: needs-rebase, size/M, verified, branch-main, can-be-merged, Stale, approved-myakove
