Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2023-01, with the labels that each got.

#1048 VMExport: add status Ready, remove token required
  ocp_resources/node.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine_export.py
Labels: size/XS, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#1047 add delete after completion annotation to dv
  ocp_resources/datavolume.py
Labels: size/S, Verified, branch-main

#1054 virt-launcher: Switch to virtqemud
  ocp_resources/virtual_machine_instance.py
Labels: size/XS, Verified, Approved-by-rnetser, branch-main

#1058 add ForbiddenError to the retry list and add default exceptions to a few calls
  ocp_resources/constants.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine.py
Labels: size/M, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#1065 Remove code-check github action, use tox
  .github/workflows/code-check.yml.old
  tox.ini
Labels: size/XS, Verified, branch-main

#1086 [v4.10] add ForbiddenError to the retry list and add default exceptions to a few calls
  ocp_resources/constants.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine.py
Labels: size/M, Verified, Approved-by-rnetser, branch-v4.10

#1084 create endpoints resource
  ocp_resources/endpoints.py
Labels: size/M, Verified, Approved-by-myakove, Approved-by-rnetser, branch-main

#1092 Rebase v4.13 on main
  .github/workflows/code-check.yml.old
  ocp_resources/constants.py
  ocp_resources/datavolume.py
  ocp_resources/endpoints.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_instance.py
  tox.ini
Labels: size/L, branch-v4.13
