Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-10, with the labels that each got.

#2126 Add UserDefinedNetwork resource using class generator
  ocp_resources/resource.py
  ocp_resources/user_defined_network.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove

#2139 Add status reason and type constants for UDN resource support
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot], commented-sbahar619, lgtm-yossisegev

#2144 Fix invalid api group
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#2141 remove unused `ValueMismatch` class
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#2146 use `uv` instead of `poetry`
  .pre-commit-config.yaml
  .release-it.json
  class_generator/README.md
  class_generator/class_generator.py
  poetry.lock
  pyproject.toml
  renovate.json
  tox.ini
  uv.lock
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser

#2152 fix: update keys_to_ignore and keys_to_rename in prepare_property_dict
  class_generator/class_generator.py
  class_generator/tests/manifests/ServingRuntime/serving_runtime.py
  class_generator/tests/test_class_generator.py
  uv.lock
Labels: size/L, verified, branch-main, can-be-merged, commented-rnetser, approved-rnetser, commented-myakove, commented-coderabbitai[bot], commented-tarukumar, lgtm-tarukumar

#2157 class-generator: per required_args check for missing arg
  class_generator/manifests/class_generator_template.j2
  class_generator/tests/manifests/Deployment/deployment.py
  class_generator/tests/manifests/Image/image_caching_internal_knative_dev.py
  class_generator/tests/manifests/Pod/pod.py
  class_generator/tests/manifests/ServiceMeshMember/service_mesh_member.py
  class_generator/tests/manifests/ServingRuntime/serving_runtime.py
  uv.lock
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser, commented-coderabbitai[bot]

#2159 Move all exceptions to `exceptions.py`
  ocp_resources/exceptions.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  tests/utils.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser

#2161 remove deprecated code
  ocp_resources/configmap.py
  ocp_resources/csidriver.py
  ocp_resources/dns.py
  ocp_resources/image.py
  ocp_resources/network.py
  ocp_resources/nmstate.py
  ocp_resources/project.py
  ocp_resources/replicaset.py
  ocp_resources/virtual_machine_Instance_replica_set.py
  ocp_resources/virtual_machine_cluster_instance_types.py
  ocp_resources/virtual_machine_cluster_preferences.py
  ocp_resources/virtual_machine_instance_types.py
  ocp_resources/virtual_machine_preferences.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser

#2163 Fix modules deprecated warn version
  ocp_resources/configmap.py
  ocp_resources/csidriver.py
  ocp_resources/dns.py
  ocp_resources/image.py
  ocp_resources/network.py
  ocp_resources/nmstate.py
  ocp_resources/project.py
  ocp_resources/replicaset.py
  ocp_resources/virtual_machine_Instance_replica_set.py
  ocp_resources/virtual_machine_cluster_instance_types.py
  ocp_resources/virtual_machine_cluster_preferences.py
  ocp_resources/virtual_machine_instance_types.py
  ocp_resources/virtual_machine_preferences.py
Labels: size/S, verified, can-be-merged, approved-rnetser, branch-v4.17

#2168 class-generator: Fix `pre-commit` run
  class_generator/class_generator.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#2167 Add wait_for_resource parameter for Resource
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#2172 Add ProjectRequest cleanup
  ocp_resources/project_request.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, lgtm-dbasunag

#2176 Add Authorino resource
  ocp_resources/authorino.py
  ocp_resources/resource.py
Labels: size/L, verified, branch-main, can-be-merged, commented-rnetser, approved-myakove, lgtm-dbasunag, commented-coderabbitai[bot]

#2145 Add Layer2 topology class
  ocp_resources/user_defined_network.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove

#2184 Add UDN layer3 class
  ocp_resources/user_defined_network.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot]
