Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-11, with the labels that each got.

#2185 Add get_alm_examples function to CSV class
  ocp_resources/cluster_service_version.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove

#2175 Minor fixes in tekton resources
  ocp_resources/pipeline.py
  ocp_resources/pipelineruns.py
  ocp_resources/task.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove

#2193 Adds LMEvalJob resource
  ocp_resources/lm_eval_job.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove

#2189 Set python>=3.9, python 3.8 is EOL
  pyproject.toml
  uv.lock
Labels: size/L, verified, branch-main

#2178 Handle sensitive information being inside a list in resource_dict
  ocp_resources/resource.py
  ocp_resources/sealed_secret.py
  ocp_resources/virtual_machine.py
  tests/test_unittests.py
  tox.toml
Labels: size/L, verified, branch-main, approved-myakove, commented-dbasunag, commented-coderabbitai[bot]
