Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-05, with the labels that each got.

#1807 Add ClusterClaim resource
  ocp_resources/cluster_claim.py
  ocp_resources/resource.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-931

#1809 Add ClusterPool resource
  ocp_resources/cluster_pool.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-940

#1811 Add ClusterDeployment resource
  ocp_resources/cluster_deployment.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-947

#1817 Add some typing to `resource.py`
  ocp_resources/cluster_claim.py
  ocp_resources/cluster_deployment.py
  ocp_resources/resource.py
  ocp_resources/sealed_secret.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-968

#1788 Add vlan and mtu parameters to OVNOverlayNetworkAttachmentDefinition
  ocp_resources/network_attachment_definition.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#1833 Add missing `from __future__ import annotations` in constant.py
  ocp_resources/constants.py
Labels: size/XS, verified, branch-main, JIRA:MSINTEROP-1027

#1827 CherryPicked: [v4.15] Add vlan and mtu parameters to OVNOverlayNetworkAttachmentDefinition
  ocp_resources/network_attachment_definition.py
Labels: size/XS, verified, can-be-merged, CherryPicked, branch-v4.15, approved-myakove

#1841 Add wait arg to cleanup
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1049

#1843 clean_up return delete function return value, delete catch `TimeoutExpiredError`
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1051

#1839 Update contributor.md and example resources
  CONTRIBUTING.md
  ocp_resources/backup.py
  ocp_resources/configmap.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove, approved-jpeimer, JIRA:MSINTEROP-1045

#1857 Add ensure_exists to resource
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1122

#1859 Fix get_client: do not send empty string to new_client_from_config_dict
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1127

#1864 Fix typing import
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1133
