Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-04, with the labels that each got.

#1697 Add vlan and mtu parameters to OVNOverlayNetworkAttachmentDefinition
  ocp_resources/network_attachment_definition.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#1761 Add `Group` resource
  ocp_resources/group.py
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#1758 Update wait_for_dv_success to work without DV Garbage Collection enabled
  ocp_resources/datavolume.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#1763 CherryPicked: [v4.15] Update wait_for_dv_success to work without DV Garbage Collection enabled
  ocp_resources/datavolume.py
Labels: size/XS, verified, can-be-merged, CherryPicked, branch-v4.15, approved-myakove

#1764 Update `get_client` code
  ocp_resources/resource.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove

#1771 CherryPicked: [v4.14] Added a new resource PerformanceProfile
  ocp_resources/performance_profile.py
  ocp_resources/resource.py
Labels: size/M, verified, can-be-merged, branch-v4.14, CherryPicked, approved-myakove

#1770 CherryPicked: [v4.15] Added a new resource PerformanceProfile
  ocp_resources/performance_profile.py
  ocp_resources/resource.py
Labels: size/M, verified, can-be-merged, CherryPicked, branch-v4.15, approved-myakove

#1782 Revert "Add vlan and mtu parameters to OVNOverlayNetworkAttachmentDefinition"
  ocp_resources/network_attachment_definition.py
Labels: size/S, branch-main

#1784 Revert "CherryPicked: [v4.15] Add vlan and mtu parameters to OVNOverlayNetworkAttachmentDefinition"
  ocp_resources/network_attachment_definition.py
Labels: size/S, branch-v4.15

#1777 Allow token creation for service accounts
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/service_account.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove, commented-dbasunag

#1794 Use dedicated exception to raise when resource is missing required args
  ocp_resources/catalog_source.py
  ocp_resources/cluster_role.py
  ocp_resources/cluster_role_binding.py
  ocp_resources/controller_revision.py
  ocp_resources/cron_job.py
  ocp_resources/csi_storage_capacity.py
  ocp_resources/data_import_cron.py
  ocp_resources/data_source.py
  ocp_resources/endpoint_slice.py
  ocp_resources/endpoints.py
  ocp_resources/image_content_source_policy.py
  ocp_resources/image_digest_mirror_set.py
  ocp_resources/ip_address_pool.py
  ocp_resources/limit_range.py
  ocp_resources/multi_cluster_observability.py
  ocp_resources/multi_network_policy.py
  ocp_resources/network_attachment_definition.py
  ocp_resources/node_health_check.py
  ocp_resources/performance_profile.py
  ocp_resources/pipeline.py
  ocp_resources/pipelineruns.py
  ocp_resources/resource.py
  ocp_resources/resource_quota.py
  ocp_resources/restore.py
  ocp_resources/role.py
  ocp_resources/storage_class.py
  ocp_resources/task_run.py
  ocp_resources/virtual_machine_clone.py
  ocp_resources/virtual_machine_export.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser
