Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-06, with the labels that each got.

#1863 Support for SelfNodeRemediationTemplate
  ocp_resources/resource.py
  ocp_resources/self_node_remediation_templates.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove

#1847 Ingress certificate related resources
  ocp_resources/ingress_controller.py
  ocp_resources/proxy.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove, commented-omrirh

#1805 Add resources ReclaimSpaceCronJob and ReclaimSpaceJob
  ocp_resources/reclaim_space_cron_job.py
  ocp_resources/reclaim_space_job.py
  ocp_resources/resource.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove

#1870 Remove error log from _ensure_exists
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#1878 Fix for typings in ARQ resources
  ocp_resources/application_aware_cluster_resource_quota.py
  ocp_resources/application_aware_resource_quota.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#1881 Fix Backup resource spec dict
  ocp_resources/backup.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1158

#1869 Adding support for fenceAgentRemediationTemplate
  ocp_resources/fence_agent_remediation_templates.py
  ocp_resources/resource.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser

#1884 Add TrustyAIService resource
  ocp_resources/resource.py
  ocp_resources/trustyai_service.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#1886 Add InferenceService resource
  ocp_resources/inference_service.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove

#1887 Add support for annotations in Resource
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove
