Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-12, with the labels that each got.

#2205 Update README.md
  class_generator/README.md
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#2209 feat: VolumeSnapshot and VolumeSnapshotClass implement
  ocp_resources/volume_snapshot.py
  ocp_resources/volume_snapshot_class.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove

#2217 increase timeout and sleep value for retry_cluster_exceptions() in patch call
  ocp_resources/benchmark.py
  ocp_resources/constants.py
  ocp_resources/pod.py
  ocp_resources/resource.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove

#2219 Update LMEvalJob resource
  ocp_resources/lm_eval_job.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot]

#2225 fix IndexError if no virt-launcher pod
  ocp_resources/virtual_machine_instance.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot]

#2226 CherryPicked: [v4.17] fix IndexError if no virt-launcher pod
  ocp_resources/virtual_machine_instance.py
Labels: size/XS, verified, can-be-merged, CherryPicked, approved-myakove, branch-v4.17

#2227 CherryPicked: [v4.16] fix IndexError if no virt-launcher pod
  ocp_resources/virtual_machine_instance.py
Labels: size/XS, verified, can-be-merged, CherryPicked, approved-myakove, branch-v4.16

#2221 class-generator: check of mandatory arg is None
  class_generator/manifests/class_generator_template.j2
  class_generator/tests/manifests/Deployment/deployment.py
  class_generator/tests/manifests/Pod/pod.py
  class_generator/tests/manifests/ServiceMeshMember/service_mesh_member.py
  class_generator/tests/manifests/ServingRuntime/serving_runtime.py
  class_generator/tests/test_class_generator.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#2228 [v4.17] increase timeout and sleep value for retry_cluster_exceptions() in patch call
  ocp_resources/benchmark.py
  ocp_resources/constants.py
  ocp_resources/pod.py
  ocp_resources/resource.py
Labels: size/S, verified, can-be-merged, approved-myakove, branch-v4.17

#2230 increase timeout and sleep value for retry_cluster_exceptions() in patch call
  ocp_resources/benchmark.py
  ocp_resources/constants.py
  ocp_resources/pod.py
  ocp_resources/resource.py
Labels: size/S, verified, can-be-merged, approved-myakove, branch-v4.16

#2232 Use testcontainers to test ocp_resources, add more test
  ocp_resources/resource.py
  pyproject.toml
  tests/test_resources.py
  tox.toml
  uv.lock
Labels: size/XL, verified, branch-main, can-be-merged, approved-rnetser

#2235 Plan: add typing
  .gitignore
  ocp_resources/plan.py
  ocp_resources/resource.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser

#2238 Use `|` for typing instead of `Optional`, Fix imports
  class_generator/class_generator.py
  class_generator/manifests/class_generator_template.j2
  class_generator/tests/manifests/APIServer/api_server.py
  class_generator/tests/manifests/ClusterOperator/cluster_operator.py
  class_generator/tests/manifests/ConfigMap/config_map.py
  class_generator/tests/manifests/DNS/dns_config_openshift_io.py
  class_generator/tests/manifests/DNS/dns_operator_openshift_io.py
  class_generator/tests/manifests/Deployment/deployment.py
  class_generator/tests/manifests/Image/image_config_openshift_io.py
  class_generator/tests/manifests/Image/image_image_openshift_io.py
  class_generator/tests/manifests/ImageContentSourcePolicy/image_content_source_policy.py
  class_generator/tests/manifests/Machine/machine.py
  class_generator/tests/manifests/NMState/nm_state.py
  class_generator/tests/manifests/OAuth/oauth.py
  class_generator/tests/manifests/Pipeline/pipeline.py
  class_generator/tests/manifests/Pod/pod.py
  class_generator/tests/manifests/Secret/secret.py
  class_generator/tests/manifests/ServiceMeshMember/service_mesh_member.py
  class_generator/tests/manifests/ServingRuntime/serving_runtime.py
  class_generator/tests/test_class_generator.py
  ocp_resources/serving_runtime.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser, commented-coderabbitai[bot]

#2244 mtv: add ova provider type
  ocp_resources/mtv.py
Labels: size/XS, verified, branch-main, commented-coderabbitai[bot]

#2242 Deprecate `privileged_client`, use client.
  ocp_resources/datavolume.py
  ocp_resources/endpoint_slice.py
  ocp_resources/endpoints.py
  ocp_resources/image_stream.py
  ocp_resources/job.py
  ocp_resources/lease.py
  ocp_resources/ocs_initialization.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/restore.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, lgtm-dbasunag

#2248 debug log would print raw data and readme is updated to reflect that
  README.md
  ocp_resources/resource.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser

#2246 MTV refactor, order files and classes
  ocp_resources/benchmark.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/endpoint_slice.py
  ocp_resources/endpoints.py
  ocp_resources/forklift_controller.py
  ocp_resources/hook.py
  ocp_resources/host.py
  ocp_resources/hostpath_provisioner.py
  ocp_resources/hyperconverged.py
  ocp_resources/image_stream.py
  ocp_resources/job.py
  ocp_resources/lease.py
  ocp_resources/machine_health_check.py
  ocp_resources/machine_set.py
  ocp_resources/migration.py
  ocp_resources/mtv.py
  ocp_resources/network_map.py
  ocp_resources/node_maintenance.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/ocs_initialization.py
  ocp_resources/operator_group.py
  ocp_resources/operator_source.py
  ocp_resources/persistent_volume_claim.py
  ocp_resources/plan.py
  ocp_resources/pod.py
  ocp_resources/pod_disruption_budget.py
  ocp_resources/priority_class.py
  ocp_resources/provider.py
  ocp_resources/resource.py
  ocp_resources/role.py
  ocp_resources/role_binding.py
  ocp_resources/route.py
  ocp_resources/secret.py
  ocp_resources/sriov_network.py
  ocp_resources/sriov_network_node_policy.py
  ocp_resources/storage_map.py
  ocp_resources/subscription.py
  ocp_resources/upload_token_request.py
  ocp_resources/utils/constants.py
  ocp_resources/utils/resource_constants.py
  ocp_resources/utils/utils.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_export.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser, lgtm-jpeimer

#2255 Add AGENT_CONNECTED constant to ResourceConstants
  ocp_resources/utils/resource_constants.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot], commented-sbahar619, lgtm-yossisegev, lgtm-Anatw

#2256 Remove unused timeout and timeout_seconds from Resource
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser
