Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-07, with the labels that each got.

#1895 update poetry to point to kubernetes 29.0.0
  poetry.lock
  pyproject.toml
Labels: size/XS, verified, can-be-merged, commented-rnetser, approved-rnetser, commented-dbasunag, approved-jpeimer, branch-v4.16

#1892 Update machine config
  ocp_resources/machine_config.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, commented-omrirh

#1889 Fix race in resource delete
  ocp_resources/resource.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove, commented-jpeimer

#1902 benchmark - add typing
  ocp_resources/benchmark.py
  ocp_resources/resource.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1177

#1904 Add more typing to resources
  CONTRIBUTING.md
  ocp_resources/catalog_source.py
  ocp_resources/cdi.py
  ocp_resources/cdi_config.py
  ocp_resources/chaos_engine.py
  ocp_resources/resource.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1178

#1907 add syncState status string inprogress to SyncStatus class
  ocp_resources/sriov_network_node_state.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#1899 CherryPicked: [v4.16] Fix race in resource delete
  ocp_resources/resource.py
Labels: size/S, verified, CherryPicked, approved-myakove, branch-v4.16

#1913 Deprecate node selector type
  ocp_resources/ingress_controller.py
  ocp_resources/resource.py
  tox.ini
Labels: size/XS, verified, can-be-merged, approved-rnetser, branch-v4.16, JIRA:MSINTEROP-1217

#1917 Enhnace the readme
  README.md
  examples/pod_example.gif
Labels: size/S, verified, branch-main, approved-myakove, JIRA:MSINTEROP-1228

#1911 Generate resource script
  .flake8
  CONTRIBUTING.md
  ocp_resources/ingress_controller.py
  ocp_resources/resource.py
  poetry.lock
  pyproject.toml
  scripts/__init__.py
  scripts/resource/README.md
  scripts/resource/__init__.py
  scripts/resource/class_generator.py
  scripts/resource/manifests/class_generator_template.j2
  scripts/resource/tests/manifests/deployment.explain
  scripts/resource/tests/manifests/deployment_expected_result.py
  scripts/resource/tests/manifests/deployment_explain_parsed.py
  scripts/resource/tests/manifests/secret.explain
  scripts/resource/tests/manifests/secret_expected_result.py
  scripts/resource/tests/manifests/secret_explain_parsed.py
  scripts/resource/tests/test_class_generator.py
  tox.ini
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1186

#1930 Remove manual run, the script needs running cluster to run
  poetry.lock
  pyproject.toml
  scripts/resource/README.md
  scripts/resource/class_generator.py
  scripts/resource/tests/manifests/deployment.explain
  scripts/resource/tests/manifests/deployment_expected_result.py
  scripts/resource/tests/manifests/deployment_explain_parsed.py
  scripts/resource/tests/manifests/secret.explain
  scripts/resource/tests/manifests/secret_expected_result.py
  scripts/resource/tests/manifests/secret_explain_parsed.py
  scripts/resource/tests/test_class_generator.py
  tox.ini
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1249

#1937 generate resource: support dry-run
  scripts/resource/class_generator.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1256

#1940 generate resource: fix docstring indent
  scripts/resource/class_generator.py
Labels: size/XS, verified, branch-main, approved-rnetser, JIRA:MSINTEROP-1258

#1935 api version - use class attr and extract api group from api version
  .gitignore
  scripts/resource/README.md
  scripts/resource/class_generator.py
  scripts/resource/manifests/class_generator_template.j2
  scripts/resource/tests/manifests/DataScienceCluster.explain
  scripts/resource/tests/manifests/Deployment.explain
  scripts/resource/tests/manifests/Pod.explain
  scripts/resource/tests/manifests/results.py
  scripts/resource/tests/test_class_generator.py
  tox.ini
Labels: size/XXL, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1251

#1942 Add tests to class_generator
  .flake8
  .gitignore
  .pre-commit-config.yaml
  scripts/resource/class_generator.py
  scripts/resource/tests/manifests/DataScienceCluster.explain
  scripts/resource/tests/manifests/Deployment-debug.json
  scripts/resource/tests/manifests/Deployment.explain
  scripts/resource/tests/manifests/Pod-debug.json
  scripts/resource/tests/manifests/Pod.explain
  scripts/resource/tests/manifests/deployment-res.py
  scripts/resource/tests/manifests/pod-res.py
  scripts/resource/tests/manifests/results.py
  scripts/resource/tests/test_class_generator.py
  tox.ini
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1268

#1944 Catch oc/kubectl exit when command failed to exit gracefully
  scripts/resource/class_generator.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1272

#1950 Refactored class_generator.py to remove debug logging and updated cla…
  scripts/resource/class_generator.py
  scripts/resource/manifests/class_generator_template.j2
  scripts/resource/tests/manifests/deployment-res.py
  scripts/resource/tests/manifests/pod-res.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1279

#1954 Add fix for API version/group typing parse
  tests/test_validate_resources.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#1956 Update tox configuration to run tests based on pull request parent br…
  tests/test_validate_resources.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1288

#1948 Update Service resource
  ocp_resources/service.py
Labels: size/XL, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1278

#1952 Update CSIDriver resource
  ocp_resources/csidriver.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1283

#1958 class_generator: add test for ConfigMap
  scripts/resource/class_generator.py
  scripts/resource/tests/manifests/ConfigMap-debug.json
  scripts/resource/tests/manifests/config_map-res.py
  scripts/resource/tests/test_class_generator.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1294

#1962 Update class_generator.py to handle output file name
  scripts/resource/class_generator.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1298

#1968 update gitignore and remove debug files
  .gitignore
  scripts/resource/debug/APIServer-debug.json
  scripts/resource/debug/apis_erver_debug.json
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1306

#1970 class_generator: Enable frop to pdb on error
  scripts/resource/class_generator.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1307

#1974 Fix camel case convert function and add tests
  scripts/resource/class_generator.py
  scripts/resource/tests/test_class_generator.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1311

#1972 class_generator: Add more interactive steps when file exists
  scripts/resource/class_generator.py
Labels: size/XS, verified, branch-main, JIRA:MSINTEROP-1309

#1960 Update SecurityContextConstraints resource
  ocp_resources/security_context_constraints.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1297

#1979 Fix camel case
  scripts/resource/class_generator.py
  scripts/resource/tests/test_class_generator.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1323

#1981 csidriver deprecate old module
  ocp_resources/csi_driver.py
  ocp_resources/csidriver.py
Labels: size/XL, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1331

#1983 Classg remove api link
  scripts/resource/README.md
  scripts/resource/class_generator.py
  scripts/resource/manifests/class_generator_template.j2
  scripts/resource/tests/manifests/api_server_res.py
  scripts/resource/tests/manifests/config_map_res.py
  scripts/resource/tests/manifests/deployment_res.py
  scripts/resource/tests/manifests/pod_res.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1334

#1987 Update SSP kind
  ocp_resources/ssp.py
Labels: size/XL, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1338

#1985 update DNS resource
  ocp_resources/dns.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1337

#1928 Add datasciencecluster
  ocp_resources/data_science_cluster.py
  ocp_resources/resource.py
Labels: size/M, verified, branch-main, can-be-merged, lgtm, approved-myakove

#1929 Add DSCInitialization
  ocp_resources/dsc_initialization.py
  ocp_resources/resource.py
Labels: size/L, verified, branch-main, can-be-merged, lgtm, approved-myakove

#1989 Add test option
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  scripts/resource/README.md
  scripts/resource/class_generator.py
  scripts/resource/tests/manifests/api_server/api_server_debug.json
  scripts/resource/tests/manifests/api_server/api_server_res.py
  scripts/resource/tests/manifests/config_map/config_map_debug.json
  scripts/resource/tests/manifests/config_map/config_map_res.py
  scripts/resource/tests/manifests/deployment/deployment_debug.json
  scripts/resource/tests/manifests/deployment/deployment_res.py
  scripts/resource/tests/manifests/pod/pod_debug.json
  scripts/resource/tests/manifests/pod/pod_res.py
  scripts/resource/tests/manifests/secret/secret_debug.json
  scripts/resource/tests/manifests/secret/secret_res.py
  scripts/resource/tests/manifests/test_parse_explain.j2
  scripts/resource/tests/test_camelcase_to_snake.py
  scripts/resource/tests/test_class_generator.py
  tox.ini
Labels: size/XL, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1339

#1977 Update Containerized Data Importer (CDI) resource
  ocp_resources/cdi.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1322

#1991 CDIConfig resource
  ocp_resources/cdi_config.py
Labels: size/XL, verified, branch-main, can-be-merged, approved-myakove

#1926 Update Node resource
  ocp_resources/node.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser, commented-omrirh

#1993 update _nodes() call to work with dict format of node_selector()
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove
