Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-03, with the labels that each got.

#1705 Fix storageProfile access_modes property
  ocp_resources/storage_profile.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#1707 CherryPicked: [v4.15] Fix storageProfile access_modes property
  ocp_resources/storage_profile.py
Labels: size/XS, verified, can-be-merged, CherryPicked, branch-v4.15, approved-myakove

#1728 retry_cluster_exceptions return real last exception
  ocp_resources/resource.py
  poetry.lock
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser

#1730 CherryPicked: [v4.15] retry_cluster_exceptions return real last exception
  ocp_resources/resource.py
  poetry.lock
Labels: size/S, verified, can-be-merged, CherryPicked, cherry-pick-v4.14, branch-v4.15, approved-myakove

#1732 Pin timeout-sampler version
  poetry.lock
  pyproject.toml
Labels: size/L, verified, branch-main, can-be-merged, cherry-pick-v4.14, cherry-pick-v4.15, approved-rnetser

#1752 Fix `get_condition_message` log
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#1757 Add suppress NotFoundError to resource create
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, commented-jpeimer

#1759 CherryPicked: [v4.15] Add suppress NotFoundError to resource create
  ocp_resources/resource.py
Labels: size/XS, verified, can-be-merged, CherryPicked, branch-v4.15, approved-myakove
