Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-08, with the labels that each got.

#1995 Update resource useing generator script
  ocp_resources/aaq.py
  ocp_resources/group.py
  ocp_resources/image.py
  ocp_resources/mtq.py
  ocp_resources/network.py
  ocp_resources/nmstate.py
  ocp_resources/oauth.py
  ocp_resources/pod.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1358

#1997 Update readme with files and attrs naming
  scripts/resource/README.md
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1361

#1999 Update resource useing generator script 2
  .pre-commit-config.yaml
  class_generator/README.md
  class_generator/__init__.py
  class_generator/class_generator.py
  class_generator/debug/.keep
  class_generator/manifests/class_generator_template.j2
  class_generator/tests/manifests/api_server/api_server_debug.json
  class_generator/tests/manifests/api_server/api_server_res.py
  class_generator/tests/manifests/cluster_operator/cluster_operator_debug.json
  class_generator/tests/manifests/cluster_operator/cluster_operator_res.py
  class_generator/tests/manifests/config_map/config_map_debug.json
  class_generator/tests/manifests/config_map/config_map_res.py
  class_generator/tests/manifests/deployment/deployment_debug.json
  class_generator/tests/manifests/deployment/deployment_res.py
  class_generator/tests/manifests/pod/pod_debug.json
  class_generator/tests/manifests/pod/pod_res.py
  class_generator/tests/manifests/secret/secret_debug.json
  class_generator/tests/manifests/secret/secret_res.py
  class_generator/tests/manifests/test_parse_explain.j2
  class_generator/tests/test_camelcase_to_snake.py
  class_generator/tests/test_class_generator.py
  ocp_resources/kubevirt.py
  ocp_resources/machine.py
  pyproject.toml
  tests/pytest.ini
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1362

#2007 Do not generate class if description in explain in <empty>
  .pre-commit-config.yaml
  class_generator/class_generator.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, JIRA:MSINTEROP-1383

#2015 Split FIELDS and SPEC in mandatory fields
  class_generator/class_generator.py
  class_generator/manifests/class_generator_template.j2
  class_generator/tests/manifests/deployment/deployment_res.py
  class_generator/tests/manifests/pod/pod_debug.json
  class_generator/tests/manifests/pod/pod_res.py
  ocp_resources/api_server.py
  ocp_resources/cdi.py
  ocp_resources/deployment.py
  ocp_resources/dsc_initialization.py
  ocp_resources/pod.py
  ocp_resources/replica_set.py
  ocp_resources/security_context_constraints.py
  ocp_resources/ssp.py
  ocp_resources/virtual_machine_cluster_instancetype.py
  ocp_resources/virtual_machine_instance_preset.py
  ocp_resources/virtual_machine_instance_replica_set.py
  ocp_resources/virtual_machine_instancetype.py
Labels: size/XL, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1393

#2005 Add support for Tekton Tasks
  ocp_resources/task.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove

#2024 cloup constraints - unify conditions
  class_generator/class_generator.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot], JIRA:MSINTEROP-1407

#2019 Update class args types to be consistent between init and docstring
  class_generator/class_generator.py
  class_generator/tests/manifests/api_server/api_server_res.py
  class_generator/tests/manifests/config_map/config_map_res.py
  class_generator/tests/manifests/deployment/deployment_res.py
  class_generator/tests/manifests/pod/pod_res.py
  class_generator/tests/manifests/secret/secret_debug.json
  class_generator/tests/manifests/secret/secret_res.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1399

#2026 pyproject: Move `pytest` dep from tests group since its used by `class-generator`
  poetry.lock
  pyproject.toml
Labels: size/XS, verified, branch-main, approved-rnetser, JIRA:MSINTEROP-1410

#2030 Classg multi kind
  class_generator/README.md
  class_generator/class_generator.py
  class_generator/tests/test_class_generator.py
  poetry.lock
Labels: size/XL, verified, branch-main, can-be-merged, approved-rnetser, commented-coderabbitai[bot], JIRA:MSINTEROP-1419

#2033 class-generator: delete temp resource file if identical to original file
  .flake8
  class_generator/class_generator.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1424

#2041 types_generator - get value from the `type` key
  class_generator/class_generator.py
  class_generator/tests/manifests/ConfigMap/config_map_res.py
  class_generator/tests/manifests/Deployment/deployment_res.py
  class_generator/tests/manifests/Pod/pod_res.py
  class_generator/tests/manifests/Secret/secret_res.py
  class_generator/tests/test_class_generator.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1441

#2049 Fix virtual_machine_preferences import
  ocp_resources/virtual_machine_preferences.py
Labels: size/XS, verified, branch-main, lgtm-dbasunag, JIRA:MSINTEROP-1445

#2054 Update dict key and add comments in jinja
  class_generator/class_generator.py
  class_generator/manifests/class_generator_template.j2
  class_generator/tests/manifests/APIServer/api_server_res.py
  class_generator/tests/manifests/ConfigMap/config_map_res.py
  class_generator/tests/manifests/Deployment/deployment_res.py
  class_generator/tests/manifests/ImageContentSourcePolicy/image_content_source_policy_res.py
  class_generator/tests/manifests/Pod/pod_res.py
  class_generator/tests/manifests/Secret/secret_res.py
  class_generator/tests/test_class_generator.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1446

#2056 Update generated resources using api schema
  ocp_resources/aaq.py
  ocp_resources/api_server.py
  ocp_resources/cdi.py
  ocp_resources/cdi_config.py
  ocp_resources/csi_driver.py
  ocp_resources/deployment.py
  ocp_resources/group.py
  ocp_resources/image_content_source_policy.py
  ocp_resources/namespace.py
  ocp_resources/oauth.py
  ocp_resources/pod.py
  ocp_resources/prometheus.py
  ocp_resources/replica_set.py
  ocp_resources/scheduler.py
  ocp_resources/service.py
  ocp_resources/ssp.py
  ocp_resources/virtual_machine_cluster_instancetype.py
  ocp_resources/virtual_machine_cluster_preference.py
  ocp_resources/virtual_machine_instance_migration.py
  ocp_resources/virtual_machine_instance_preset.py
  ocp_resources/virtual_machine_instance_replica_set.py
  ocp_resources/virtual_machine_instancetype.py
  ocp_resources/virtual_machine_preference.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot], JIRA:MSINTEROP-1450

#2029 Add MariaDB resource
  ocp_resources/maria_db.py
  ocp_resources/resource.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-myakove

#2028 Add MariadbOperator Resource
  ocp_resources/mariadb_operator.py
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#2071 Get group from `x-kubernetes-group-version-kind` list
  class_generator/class_generator.py
  class_generator/tests/manifests/Image/image_config_openshift_io.py
  class_generator/tests/manifests/Image/image_image_openshift_io.py
  class_generator/tests/test_class_generator.py
  ocp_resources/image.py
  ocp_resources/image_config_openshift_io.py
  ocp_resources/image_image_openshift_io.py
  ocp_resources/node.py
  ocp_resources/node_config_openshift_io.py
  ocp_resources/project.py
  ocp_resources/project_config_openshift_io.py
  ocp_resources/project_project_openshift_io.py
  tests/test_validate_resources.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1488

#2073 class_generator - add `object` as field type
  .github/in-solidarity.yml
  class_generator/class_generator.py
  class_generator/tests/manifests/APIServer/api_server.py
  class_generator/tests/manifests/ConfigMap/config_map.py
  class_generator/tests/manifests/DNS/dns_config_openshift_io.py
  class_generator/tests/manifests/DNS/dns_operator_openshift_io.py
  class_generator/tests/manifests/Deployment/deployment.py
  class_generator/tests/manifests/Image/image_config_openshift_io.py
  class_generator/tests/manifests/Image/image_image_openshift_io.py
  class_generator/tests/manifests/Machine/machine.py
  class_generator/tests/manifests/NMState/nm_state.py
  class_generator/tests/manifests/Pod/pod.py
  class_generator/tests/manifests/Secret/secret.py
  ocp_resources/kubevirt.py
  ocp_resources/network_config_openshift_io.py
  ocp_resources/network_operator_openshift_io.py
  ocp_resources/nm_state.py
  ocp_resources/security_context_constraints.py
  ocp_resources/service.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-myakove, JIRA:MSINTEROP-1497

#2069 clean_up, add `timeout` arg
  ocp_resources/project.py
  ocp_resources/project_project_openshift_io.py
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, lgtm-omrirh, commented-coderabbitai[bot], JIRA:MSINTEROP-1487

#2076 Fix validate_resource script
  tests/scripts/resources_definitions.json
  tests/scripts/update_resources_definitions.py
  tests/scripts/validate_resources.py
  tests/test_validate_resources.py
  tests/test_validate_resources_script.py
  tox.ini
Labels: size/XL, verified, branch-main, can-be-merged, approved-rnetser, commented-coderabbitai[bot], JIRA:MSINTEROP-1508

#2080 class-generator: remove minimum cluster version in update-schema
  class_generator/class_generator.py
Labels: size/XS, verified, branch-main, JIRA:MSINTEROP-1523

#2086 Minor fix: Add steps as Optional in __init__
  ocp_resources/task.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot]
