Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-01, with the labels that each got.

#1565 Test resources use k3d in tox
  tox.ini
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#1559 Remove timeout sampler tests
  tests/unittests/test_utils.py
  tox.ini
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser

#1567 Add more test for resources
  .flake8
  tests/conftest.py
  tests/pytest.ini
  tests/test_resources.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser

#1528 Update controller_revision class constructor, documentation and add 'to_dict' parameters validation
  ocp_resources/controller_revision.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove, approved-omrirh

#1541 Add data mover params to backup
  ocp_resources/backup.py
Labels: needs-rebase, size/S, verified, branch-main, can-be-merged, approved-myakove

#1569 Adding topology option to the overlay NAD
  ocp_resources/network_attachment_definition.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#1572 Refactor cherry-pick option in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#1580 Update poetry
  poetry.lock
Labels: size/XL, branch-main

#1501 Updated NodeHealthCheck with desired fields and add self node remediation api
  ocp_resources/node_health_check.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove

#1585 stale: set to 30 days
  .github/workflows/close-stale-issues.yml
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#1606 [4.15] Use timeout_sampler module
  ocp_resources/benchmark.py
  ocp_resources/cdi_config.py
  ocp_resources/daemonset.py
  ocp_resources/datavolume.py
  ocp_resources/deployment.py
  ocp_resources/machine_set.py
  ocp_resources/mtv.py
  ocp_resources/node_network_configuration_policy.py
  ocp_resources/node_network_state.py
  ocp_resources/pod.py
  ocp_resources/resource.py
  ocp_resources/sriov_network_node_state.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_import.py
  ocp_resources/virtual_machine_instance.py
  ocp_resources/virtual_machine_restore.py
  ocp_resources/virtual_machine_snapshot.py
  poetry.lock
  pyproject.toml
  tests/unittests/test_utils.py
Labels: size/M, verified, can-be-merged, branch-v4.15, approved-myakove, commented-jpeimer

#1603 Move `resources-definitions` update script to this repository
  .flake8
  tests/scripts/__init__.py
  tests/scripts/resources_definitions.json
  tests/scripts/update_resources_definitions.py
  tests/test_validate_resources.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser

#1607 Move `resources-definitions` update script to this repository (#1603)
  .flake8
  tests/scripts/__init__.py
  tests/scripts/resources_definitions.json
  tests/scripts/update_resources_definitions.py
  tests/test_validate_resources.py
Labels: size/M, verified, can-be-merged, cherry-pick-v4.14, branch-v4.15, approved-rnetser

#1609 Move `resources-definitions` update script to this repository (#1603)…
  .flake8
  tests/scripts/__init__.py
  tests/scripts/resources_definitions.json
  tests/scripts/update_resources_definitions.py
  tests/test_validate_resources.py
Labels: size/M, verified, can-be-merged, branch-v4.14, approved-rnetser

#1611 Remove unused Dockerfile
  Dockerfile
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#1601 Add Datasource bootsource property
  .flake8
  ocp_resources/data_source.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#1621 Add Datasource bootsource property (#1601)
  ocp_resources/data_source.py
Labels: size/M, verified, can-be-merged, branch-v4.15, approved-rnetser

#1628 Add Datasource bootsource property (#1601) (#1621)
  ocp_resources/data_source.py
Labels: size/M, verified, can-be-merged, branch-v4.14, approved-myakove
