Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2024-09, with the labels that each got.

#2118 Pin kubernetes version to 27.x.x
  poetry.lock
  pyproject.toml
Labels: size/XS, verified, can-be-merged, branch-v4.14, approved-rnetser

#2116 Pin kubernetes version to 28.x.x
  poetry.lock
  pyproject.toml
Labels: size/S, verified, can-be-merged, branch-v4.15, approved-rnetser

#2114 Pin kubernetes version to 29.x.x
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: size/XS, verified, can-be-merged, approved-rnetser, branch-v4.16

#2121 feat(class_generator): Add support for parsing user code from generat…
  class_generator/class_generator.py
  class_generator/manifests/class_generator_template.j2
  class_generator/tests/manifests/APIServer/api_server.py
  class_generator/tests/manifests/ClusterOperator/cluster_operator.py
  class_generator/tests/manifests/ConfigMap/config_map.py
  class_generator/tests/manifests/DNS/dns_config_openshift_io.py
  class_generator/tests/manifests/DNS/dns_operator_openshift_io.py
  class_generator/tests/manifests/Deployment/deployment.py
  class_generator/tests/manifests/Image/image_caching_internal_knative_dev.py
  class_generator/tests/manifests/Image/image_config_openshift_io.py
  class_generator/tests/manifests/Image/image_image_openshift_io.py
  class_generator/tests/manifests/ImageContentSourcePolicy/image_content_source_policy.py
  class_generator/tests/manifests/Machine/machine.py
  class_generator/tests/manifests/NMState/nm_state.py
  class_generator/tests/manifests/Pod/pod.py
  class_generator/tests/manifests/Secret/secret.py
  class_generator/tests/manifests/ServiceMeshMember/service_mesh_member.py
Labels: verified, branch-main, can-be-merged, approved-rnetser, commented-myakove, commented-coderabbitai[bot]

#2107 update to config map to make data value hashed
  ocp_resources/config_map.py
  ocp_resources/configmap.py
Labels: verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#2109 point main to kubernetes 1.30, since no wrapper branch points to it currently
  poetry.lock
  pyproject.toml
Labels: verified, branch-main, can-be-merged, approved-myakove

#2127 fix(Validate resources during testing): Handle missing resource cases
  tests/scripts/validate_resources.py
Labels: size/XS, verified, branch-main

#2129 feat(class_generator): Format API group name consistently
  class_generator/class_generator.py
  tests/scripts/validate_resources.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, commented-myakove, commented-coderabbitai[bot]

#2131 test ApiGroup names order
  ocp_resources/resource.py
  tests/test_api_group_order.py
  tox.ini
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser

#2134 Pre commit ci update config
  .gitleaks.toml
  .pre-commit-config.yaml
Labels: size/XS, verified, branch-main, commented-coderabbitai[bot]
