Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2025-04, with the labels that each got.

#2371 fix: get_client() client_configuration
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#2374 feat: Add KubeletConfig resource
  ocp_resources/kubelet_config.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, lgtm-dbasunag, commented-coderabbitai[bot]

#2376 fix: Update virtual_machine.py example
  examples/virtual_machine.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove

#2385 feat: add MTC resources: MigMigration, DirectVolumeMigration, DirectVolumeMigrationProgress, MigAnalytic
  ocp_resources/direct_volume_migration.py
  ocp_resources/direct_volume_migration_progress.py
  ocp_resources/mig_analytic.py
  ocp_resources/mig_migration.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-rnetser

#2389 feat: add SelfSubjectReview resource
  ocp_resources/resource.py
  ocp_resources/self_subject_review.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove, lgtm-dbasunag, lgtm-myakove
