Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2025-01, with the labels that each got.

#2240 Add retry for api_request() call
  ocp_resources/resource.py
  ocp_resources/utils/constants.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_instance.py
Labels: size/M, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove

#2262 Add retry for api_request() call
  ocp_resources/constants.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_instance.py
Labels: size/M, verified, can-be-merged, approved-rnetser, approved-myakove, branch-v4.17, lgtm-jpeimer

#2267 Fix deploy function of NNCP
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, approved-myakove, commented-coderabbitai[bot]

#2269 CherryPicked: [v4.17] Fix deploy function of NNCP
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, verified, can-be-merged, CherryPicked, approved-myakove, branch-v4.17

#2264 VirtualMachineExport - update with class_generator
  ocp_resources/virtual_machine_export.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove, commented-jpeimer, commented-coderabbitai[bot]

#2271 update pyhelper-utils
  poetry.lock
  pyproject.toml
Labels: size/XXL, verified, can-be-merged, approved-myakove, branch-v4.17

#2273 Add retry for api_request() call (#2240)
  ocp_resources/constants.py
  ocp_resources/resource.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_instance.py
Labels: size/M, verified, can-be-merged, approved-myakove, branch-v4.16

#2265 UDN: add wait_for_network_ready
  ocp_resources/user_defined_network.py
  ocp_resources/utils/resource_constants.py
Labels: size/XS, verified, branch-main

#2277 deprecate class MissingResourceResError
  ocp_resources/exceptions.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot], lgtm-jpeimer

#2270 Pass sleep_time as argument in wait_for_condition method
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#2281 Always check if arg is not None
  class_generator/manifests/class_generator_template.j2
  class_generator/tests/manifests/APIServer/api_server.py
  class_generator/tests/manifests/ConfigMap/config_map.py
  class_generator/tests/manifests/DNS/dns_config_openshift_io.py
  class_generator/tests/manifests/DNS/dns_operator_openshift_io.py
  class_generator/tests/manifests/Deployment/deployment.py
  class_generator/tests/manifests/Image/image_config_openshift_io.py
  class_generator/tests/manifests/Image/image_image_openshift_io.py
  class_generator/tests/manifests/ImageContentSourcePolicy/image_content_source_policy.py
  class_generator/tests/manifests/Machine/machine.py
  class_generator/tests/manifests/NMState/nm_state.py
  class_generator/tests/manifests/OAuth/oauth.py
  class_generator/tests/manifests/Pod/pod.py
  class_generator/tests/manifests/Secret/secret.py
  class_generator/tests/manifests/ServingRuntime/serving_runtime.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser

#2285 Add test for class-generator scripts
  class_generator/scripts/tests/test_scripts.py
  class_generator/scripts/tools.py
  tox.toml
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser, commented-myakove, commented-coderabbitai[bot]

#2279 Regenerate dataimportcron resource
  ocp_resources/data_import_cron.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot]

#2253 add deprecation warning for remove garbage collector dead code
  ocp_resources/datavolume.py
Labels: size/XS, verified, branch-main, can-be-merged, Stale, commented-rnetser, approved-rnetser, approved-myakove, commented-dbasunag, lgtm-dbasunag

#2300 CherryPicked: [v4.16] Update wait_for_status_success() call to look at both type and status for status.conditions
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, verified, can-be-merged, CherryPicked, approved-myakove, branch-v4.16

#2301 update to clean_up() call in node_network_configuration_policy.py
  ocp_resources/node_network_configuration_policy.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#2291 Add proxy support to Kubernetes client configuration in get_client
  README.md
  ocp_resources/resource.py
  tests/test_resources.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove, commented-myakove, commented-dbasunag, commented-coderabbitai[bot], commented-sbahar619, commented-EdDev

#2303 Run all tests at once to get better coverage overview
  pyproject.toml
  tests/test_resources.py
  tox.toml
Labels: size/L, verified, branch-main

#2305 better error client when proxy has conflict
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main
