Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2025-03, with the labels that each got.

#2329 fix: Update IPAM attribute to align with UDN API changes
  ocp_resources/user_defined_network.py
Labels: size/XS, verified, branch-main, approved-myakove, commented-sbahar619

#2344 feat: Add StorageCluster resource
  ocp_resources/storage_cluster.py
Labels: size/L, verified, branch-main, commented-coderabbitai[bot], lgtm-jpeimer

#2347 fix: Avoid race when removing interfaces via NNCP
  .flake8
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, verified, branch-main, approved-myakove, commented-coderabbitai[bot], lgtm-sbahar619

#2354 fix: Avoid race when removing interfaces via NNCP
  .flake8
  ocp_resources/node_network_configuration_policy.py
Labels: size/S, verified, can-be-merged, approved-myakove, branch-v4.18

#2352 fix: escape docstring with `r` for generated resources using class-generator
  class_generator/manifests/class_generator_template.j2
  class_generator/tests/manifests/APIServer/api_server.py
  class_generator/tests/manifests/ConfigMap/config_map.py
  class_generator/tests/manifests/DNS/dns_config_openshift_io.py
  class_generator/tests/manifests/DNS/dns_operator_openshift_io.py
  class_generator/tests/manifests/Deployment/deployment.py
  class_generator/tests/manifests/Image/image_config_openshift_io.py
  class_generator/tests/manifests/Image/image_image_openshift_io.py
  class_generator/tests/manifests/ImageContentSourcePolicy/image_content_source_policy.py
  class_generator/tests/manifests/Machine/machine.py
  class_generator/tests/manifests/NMState/nm_state.py
  class_generator/tests/manifests/OAuth/oauth.py
  class_generator/tests/manifests/Pod/pod.py
  class_generator/tests/manifests/Secret/secret.py
  class_generator/tests/manifests/ServiceMeshMember/service_mesh_member.py
  class_generator/tests/manifests/ServingRuntime/serving_runtime.py
  ocp_resources/pod.py
Labels: size/L, verified, branch-main

#2358 fix: Do not set signal when not in main thread
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#2355 feat: Add ClusterResourceQuota
  ocp_resources/cluster_resource_quota.py
  ocp_resources/resource.py
Labels: size/M, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot]

#2356 ci: add script to generate changelog for new release
  .flake8
  .release-it.json
  scripts/generate_changelog.py
  scripts/k3d-runner.sh
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser

#2361 feat: Add InferenceGraph resource
  ocp_resources/inference_graph.py
Labels: size/M, branch-main, commented-coderabbitai[bot]

#2362 fix: class_generator: remove `please add description`
  class_generator/class_generator.py
  class_generator/tests/manifests/Pipeline/pipeline.py
  class_generator/tests/manifests/ServiceMeshMember/service_mesh_member.py
  class_generator/tests/manifests/ServingRuntime/serving_runtime.py
Labels: size/S, verified, branch-main, can-be-merged, approved-rnetser
