Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2025-02, with the labels that each got.

#2307 Fix test regex for proxy error message
  tests/test_resources.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove

#2308 Add condition.type SUCCEEDED
  ocp_resources/utils/resource_constants.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#2311 DataVolume: Change default value for argument dv_garbage_collection_enabled in wait_for_dv_success() call
  ocp_resources/datavolume.py
Labels: size/XS, verified, branch-main, can-be-merged, commented-rnetser, approved-rnetser, commented-myakove, commented-dbasunag

#2320 Add conventional-precommit-linter to pre-commit.
  .pre-commit-config.yaml
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser

#2318 Add new nncp, fix import imports from existing resource
  class_generator/class_generator.py
  ocp_resources/node_network_configuration_policy_latest.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser, commented-coderabbitai[bot]

#2322 feat: Use git cliff to generate the change log.
  .release-it.json
  README.md
  cliff.toml
Labels: size/L, branch-main

#2324 Revert "feat: Use git cliff to generate the change log."
  .release-it.json
  README.md
  cliff.toml
Labels: size/L, branch-main

#2331 Add Kubeflow Notebook CR
  ocp_resources/notebook.py
  ocp_resources/resource.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove

#2332 fix: v4.18 branch should pin to kubernetes 31.*.*
  pyproject.toml
  uv.lock
Labels: size/M, verified, can-be-merged, approved-myakove, branch-v4.18

#2337 feat: Add console config and console operator resources
  ocp_resources/console_config_openshift_io.py
  ocp_resources/console_operator_openshift_io.py
Labels: size/L, verified, branch-main
