Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2025-08, with the labels that each got.

#2482 feat: Add a status field to the backup resource
  ocp_resources/utils/resource_constants.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, lgtm-myakove

#2486 feat: Add Config resources
  ocp_resources/config_imageregistry_operator_openshift_io.py
  ocp_resources/config_operator_openshift_io.py
  ocp_resources/config_samples_operator_openshift_io.py
  ocp_resources/resource.py
Labels: size/XL, verified, branch-main, can-be-merged, commented-rnetser, approved-myakove, commented-dbasunag, lgtm-myakove

#2490 feat: add RouteAdvertisements and FRRConfiguration classes
  ocp_resources/frr_configuration.py
  ocp_resources/resource.py
  ocp_resources/route_advertisements.py
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot]

#2499 refactor(wait_for_status): Use self.instance to get status
  ocp_resources/resource.py
Labels: size/S, verified, branch-main, can-be-merged, approved-myakove

#2479 fix: make PVC Bound timeout configurable in wait_for_dv_success
  ocp_resources/datavolume.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, lgtm-rnetser

#2509 feat: Add support for volumes in job resource
  ocp_resources/job.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser
