Repository RedHatQE/openshift-python-wrapper, pull requests merged in 2025-07, with the labels that each got.

#2429 fix: class-generator duplicate resources on update schema
  class_generator/class_generator.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-rnetser, lgtm-rnetser

#2440 fix: remove unused project deps
  pyproject.toml
  uv.lock
Labels: size/L, verified, branch-main, can-be-merged, approved-myakove

#2444 feat: ProjectRequest to return Project on deploy
  ocp_resources/project_request.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, lgtm-myakove

#2448 CherryPicked: [v4.19] feat: ProjectRequest to return Project on deploy
  ocp_resources/project_request.py
Labels: size/XS, verified, can-be-merged, CherryPicked, approved-rnetser, lgtm-rnetser, branch-v4.19

#2437 feat: add ResourceList and NamespacedResourceList classes
  examples/resource_list.py
  ocp_resources/resource.py
  tests/test_resource.py
Labels: size/L, verified, branch-main, can-be-merged, approved-rnetser, lgtm-myakove, lgtm-rnetser

#2451 fix: Add missing typing for already typed functions
  class_generator/class_generator.py
  ocp_resources/application_aware_cluster_resource_quota.py
  ocp_resources/application_aware_resource_quota.py
  ocp_resources/backup.py
  ocp_resources/benchmark.py
  ocp_resources/cdi_config.py
  ocp_resources/chaos_engine.py
  ocp_resources/cluster_deployment.py
  ocp_resources/cluster_pool.py
  ocp_resources/cluster_service_version.py
  ocp_resources/config_map.py
  ocp_resources/deployment.py
  ocp_resources/fence_agent_remediation_templates.py
  ocp_resources/image_caching_internal_knative_dev.py
  ocp_resources/inference_service.py
  ocp_resources/ingress_controller.py
  ocp_resources/machine.py
  ocp_resources/machine_config.py
  ocp_resources/model_registry.py
  ocp_resources/mtq.py
  ocp_resources/node.py
  ocp_resources/node_maintenance.py
  ocp_resources/node_network_configuration_policy_latest.py
  ocp_resources/plan.py
  ocp_resources/pod.py
  ocp_resources/project_request.py
  ocp_resources/provider.py
  ocp_resources/proxy.py
  ocp_resources/reclaim_space_cron_job.py
  ocp_resources/reclaim_space_job.py
  ocp_resources/resource.py
  ocp_resources/sealed_secret.py
  ocp_resources/service_serving_knative_dev.py
  ocp_resources/task.py
  ocp_resources/trustyai_service.py
  ocp_resources/user_defined_network.py
  ocp_resources/utils/constants.py
  ocp_resources/virtual_machine.py
  ocp_resources/virtual_machine_instance.py
  pyproject.toml
  tests/scripts/validate_resources.py
  tests/test_api_group_order.py
  tests/test_resource.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-myakove

#2463 feat: class-generator - discover and generate missing resources from cluster
  class_generator/README.md
  class_generator/class_generator.py
  class_generator/tests/test_resource_discovery.py
Labels: size/XXL, verified, branch-main, can-be-merged, approved-myakove, commented-coderabbitai[bot]

#2467 docs: update install instructions to use uv in README
  README.md
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove, lgtm-myakove

#2468 fix: return type Self for functions that return self
  class_generator/class_generator.py
  class_generator/scripts/tests/test_scripts.py
  ocp_resources/project_request.py
  ocp_resources/resource.py
Labels: size/XS, verified, branch-main, can-be-merged, approved-myakove
